// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/v1/auth.proto

package grpc_welaw_v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type UserRole struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *UserRole) Reset()                    { *m = UserRole{} }
func (m *UserRole) String() string            { return proto.CompactTextString(m) }
func (*UserRole) ProtoMessage()               {}
func (*UserRole) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *UserRole) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type LoginRequest struct {
}

func (m *LoginRequest) Reset()                    { *m = LoginRequest{} }
func (m *LoginRequest) String() string            { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()               {}
func (*LoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

type LoginReply struct {
	State string `protobuf:"bytes,1,opt,name=state" json:"state,omitempty"`
	Url   string `protobuf:"bytes,2,opt,name=url" json:"url,omitempty"`
	Err   string `protobuf:"bytes,3,opt,name=err" json:"err,omitempty"`
}

func (m *LoginReply) Reset()                    { *m = LoginReply{} }
func (m *LoginReply) String() string            { return proto.CompactTextString(m) }
func (*LoginReply) ProtoMessage()               {}
func (*LoginReply) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *LoginReply) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *LoginReply) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *LoginReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type LoginUserRequest struct {
	State string `protobuf:"bytes,1,opt,name=state" json:"state,omitempty"`
	Code  string `protobuf:"bytes,2,opt,name=code" json:"code,omitempty"`
}

func (m *LoginUserRequest) Reset()                    { *m = LoginUserRequest{} }
func (m *LoginUserRequest) String() string            { return proto.CompactTextString(m) }
func (*LoginUserRequest) ProtoMessage()               {}
func (*LoginUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *LoginUserRequest) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *LoginUserRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type LoginUserReply struct {
	Authorization *Authorization `protobuf:"bytes,1,opt,name=authorization" json:"authorization,omitempty"`
	Err           string         `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
}

func (m *LoginUserReply) Reset()                    { *m = LoginUserReply{} }
func (m *LoginUserReply) String() string            { return proto.CompactTextString(m) }
func (*LoginUserReply) ProtoMessage()               {}
func (*LoginUserReply) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *LoginUserReply) GetAuthorization() *Authorization {
	if m != nil {
		return m.Authorization
	}
	return nil
}

func (m *LoginUserReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type MakeTokenRequest struct {
	Uid string `protobuf:"bytes,1,opt,name=uid" json:"uid,omitempty"`
}

func (m *MakeTokenRequest) Reset()                    { *m = MakeTokenRequest{} }
func (m *MakeTokenRequest) String() string            { return proto.CompactTextString(m) }
func (*MakeTokenRequest) ProtoMessage()               {}
func (*MakeTokenRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *MakeTokenRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type MakeTokenReply struct {
	Token string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	Url   string `protobuf:"bytes,2,opt,name=url" json:"url,omitempty"`
	Err   string `protobuf:"bytes,3,opt,name=err" json:"err,omitempty"`
}

func (m *MakeTokenReply) Reset()                    { *m = MakeTokenReply{} }
func (m *MakeTokenReply) String() string            { return proto.CompactTextString(m) }
func (*MakeTokenReply) ProtoMessage()               {}
func (*MakeTokenReply) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *MakeTokenReply) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *MakeTokenReply) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *MakeTokenReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type Authorization struct {
	Uid        string `protobuf:"bytes,1,opt,name=uid" json:"uid,omitempty"`
	Username   string `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	Email      string `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
	FullName   string `protobuf:"bytes,4,opt,name=full_name,json=fullName" json:"full_name,omitempty"`
	PictureUrl string `protobuf:"bytes,8,opt,name=picture_url,json=pictureUrl" json:"picture_url,omitempty"`
	ProviderId string `protobuf:"bytes,9,opt,name=provider_id,json=providerId" json:"provider_id,omitempty"`
	Name       string `protobuf:"bytes,10,opt,name=name" json:"name,omitempty"`
}

func (m *Authorization) Reset()                    { *m = Authorization{} }
func (m *Authorization) String() string            { return proto.CompactTextString(m) }
func (*Authorization) ProtoMessage()               {}
func (*Authorization) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

func (m *Authorization) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *Authorization) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Authorization) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Authorization) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *Authorization) GetPictureUrl() string {
	if m != nil {
		return m.PictureUrl
	}
	return ""
}

func (m *Authorization) GetProviderId() string {
	if m != nil {
		return m.ProviderId
	}
	return ""
}

func (m *Authorization) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type LoginAsRequest struct {
	Authorization *Authorization `protobuf:"bytes,1,opt,name=authorization" json:"authorization,omitempty"`
}

func (m *LoginAsRequest) Reset()                    { *m = LoginAsRequest{} }
func (m *LoginAsRequest) String() string            { return proto.CompactTextString(m) }
func (*LoginAsRequest) ProtoMessage()               {}
func (*LoginAsRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8} }

func (m *LoginAsRequest) GetAuthorization() *Authorization {
	if m != nil {
		return m.Authorization
	}
	return nil
}

type LoginAsReply struct {
	Err string `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
}

func (m *LoginAsReply) Reset()                    { *m = LoginAsReply{} }
func (m *LoginAsReply) String() string            { return proto.CompactTextString(m) }
func (*LoginAsReply) ProtoMessage()               {}
func (*LoginAsReply) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{9} }

func (m *LoginAsReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type LogoutRequest struct {
}

func (m *LogoutRequest) Reset()                    { *m = LogoutRequest{} }
func (m *LogoutRequest) String() string            { return proto.CompactTextString(m) }
func (*LogoutRequest) ProtoMessage()               {}
func (*LogoutRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{10} }

type LogoutReply struct {
	Err string `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
}

func (m *LogoutReply) Reset()                    { *m = LogoutReply{} }
func (m *LogoutReply) String() string            { return proto.CompactTextString(m) }
func (*LogoutReply) ProtoMessage()               {}
func (*LogoutReply) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{11} }

func (m *LogoutReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func init() {
	proto.RegisterType((*UserRole)(nil), "grpc.welaw.v1.UserRole")
	proto.RegisterType((*LoginRequest)(nil), "grpc.welaw.v1.LoginRequest")
	proto.RegisterType((*LoginReply)(nil), "grpc.welaw.v1.LoginReply")
	proto.RegisterType((*LoginUserRequest)(nil), "grpc.welaw.v1.LoginUserRequest")
	proto.RegisterType((*LoginUserReply)(nil), "grpc.welaw.v1.LoginUserReply")
	proto.RegisterType((*MakeTokenRequest)(nil), "grpc.welaw.v1.MakeTokenRequest")
	proto.RegisterType((*MakeTokenReply)(nil), "grpc.welaw.v1.MakeTokenReply")
	proto.RegisterType((*Authorization)(nil), "grpc.welaw.v1.Authorization")
	proto.RegisterType((*LoginAsRequest)(nil), "grpc.welaw.v1.LoginAsRequest")
	proto.RegisterType((*LoginAsReply)(nil), "grpc.welaw.v1.LoginAsReply")
	proto.RegisterType((*LogoutRequest)(nil), "grpc.welaw.v1.LogoutRequest")
	proto.RegisterType((*LogoutReply)(nil), "grpc.welaw.v1.LogoutReply")
}

func init() { proto.RegisterFile("api/v1/auth.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 381 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0x41, 0x4f, 0xf2, 0x40,
	0x10, 0x4d, 0x81, 0xef, 0x0b, 0x0c, 0x16, 0x71, 0xe3, 0xa1, 0x51, 0x23, 0xa4, 0xf1, 0xe0, 0xa9,
	0x04, 0xbd, 0x7a, 0xc1, 0x83, 0x89, 0x06, 0x3d, 0x34, 0x70, 0x26, 0x2b, 0x1d, 0x70, 0xc3, 0xc2,
	0xd6, 0xed, 0x16, 0xa2, 0x3f, 0xd0, 0xdf, 0x65, 0x76, 0xbb, 0x0b, 0xc5, 0x68, 0xe2, 0xc1, 0xdb,
	0xcc, 0xeb, 0xbc, 0xb7, 0x33, 0x6f, 0xa6, 0x70, 0x44, 0x53, 0xd6, 0x5b, 0xf7, 0x7b, 0x34, 0x57,
	0x2f, 0x51, 0x2a, 0x85, 0x12, 0xc4, 0x9f, 0xcb, 0x74, 0x1a, 0x6d, 0x90, 0xd3, 0x4d, 0xb4, 0xee,
	0x87, 0xe7, 0x50, 0x1f, 0x67, 0x28, 0x63, 0xc1, 0x91, 0x10, 0xa8, 0xad, 0xe8, 0x12, 0x03, 0xaf,
	0xeb, 0x5d, 0x36, 0x62, 0x13, 0x87, 0x2d, 0x38, 0x18, 0x8a, 0x39, 0x5b, 0xc5, 0xf8, 0x9a, 0x63,
	0xa6, 0xc2, 0x3b, 0x00, 0x9b, 0xa7, 0xfc, 0x8d, 0x1c, 0xc3, 0xbf, 0x4c, 0x51, 0xe5, 0x28, 0x45,
	0x42, 0xda, 0x50, 0xcd, 0x25, 0x0f, 0x2a, 0x06, 0xd3, 0xa1, 0x46, 0x50, 0xca, 0xa0, 0x5a, 0x20,
	0x28, 0x65, 0x78, 0x03, 0x6d, 0xa3, 0x63, 0x1e, 0x2f, 0xb4, 0x7f, 0x50, 0x23, 0x50, 0x9b, 0x8a,
	0x04, 0xad, 0x9c, 0x89, 0xc3, 0x19, 0xb4, 0x4a, 0x6c, 0xdd, 0xc9, 0x2d, 0xf8, 0x7a, 0x48, 0x21,
	0xd9, 0x3b, 0x55, 0x4c, 0xac, 0x8c, 0x46, 0xf3, 0xea, 0x2c, 0xda, 0x1b, 0x37, 0x1a, 0x94, 0x6b,
	0xe2, 0x7d, 0x8a, 0xeb, 0xb2, 0xb2, 0xeb, 0xf2, 0x02, 0xda, 0x8f, 0x74, 0x81, 0x23, 0xb1, 0x40,
	0xe7, 0x80, 0x99, 0x8e, 0x25, 0xb6, 0x47, 0x1d, 0x86, 0x0f, 0xd0, 0x2a, 0x55, 0x59, 0x5f, 0x94,
	0xce, 0xdc, 0x24, 0x26, 0xf9, 0x95, 0x2f, 0x1f, 0x1e, 0xf8, 0x83, 0xaf, 0x5d, 0xed, 0xbf, 0x47,
	0x4e, 0xa0, 0x9e, 0x67, 0x28, 0xcd, 0xae, 0x0a, 0xb1, 0x6d, 0xae, 0x5f, 0xc6, 0x25, 0x65, 0xdc,
	0x6a, 0x16, 0x09, 0x39, 0x85, 0xc6, 0x2c, 0xe7, 0x7c, 0x62, 0x28, 0xb5, 0x82, 0xa2, 0x81, 0x27,
	0x4d, 0xe9, 0x40, 0x33, 0x65, 0x53, 0x95, 0x4b, 0x9c, 0xe8, 0xf6, 0xea, 0xe6, 0x33, 0x58, 0x68,
	0x2c, 0xb9, 0x29, 0x90, 0x62, 0xcd, 0x12, 0x94, 0x13, 0x96, 0x04, 0x0d, 0x5b, 0x60, 0xa1, 0xfb,
	0x64, 0x7b, 0x38, 0x50, 0x3a, 0x9c, 0x91, 0x5d, 0xd1, 0x20, 0x73, 0xc6, 0xfd, 0xc1, 0x8a, 0xc2,
	0xae, 0x3d, 0x47, 0xad, 0xaa, 0x8d, 0xb6, 0x06, 0x7a, 0x3b, 0x03, 0x0f, 0xc1, 0x1f, 0x8a, 0xb9,
	0xc8, 0x95, 0xbb, 0xd8, 0x0e, 0x34, 0x1d, 0xf0, 0x2d, 0xe3, 0xf9, 0xbf, 0xf9, 0x31, 0xae, 0x3f,
	0x03, 0x00, 0x00, 0xff, 0xff, 0x55, 0xdf, 0xf9, 0xa1, 0x2d, 0x03, 0x00, 0x00,
}
