// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/admin.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	proto/admin.proto
	proto/auth.proto
	proto/ballot.proto
	proto/comments.proto
	proto/law.proto
	proto/upstream.proto
	proto/user.proto
	proto/welaw.proto

It has these top-level messages:
	ServerStats
	LoadReposOptions
	LoadReposReply
	SaveReposOptions
	SaveReposReply
	UserRole
	LoginRequest
	LoginReply
	LoginUserRequest
	LoginUserReply
	MakeTokenRequest
	MakeTokenReply
	Authorization
	LoginAsRequest
	LoginAsReply
	LogoutRequest
	LogoutReply
	Vote
	VoteSummary
	CreateVotesOptions
	VoteResult
	CreateVoteOptions
	CreateVoteRequest
	CreateVoteReply
	DeleteVoteOptions
	DeleteVoteRequest
	DeleteVoteReply
	GetVoteOptions
	GetVoteRequest
	GetVoteReply
	ListVotesOptions
	ListVotesRequest
	ListVotesReply
	UpdateVoteOptions
	UpdateVoteRequest
	UpdateVoteReply
	Comment
	ListCommentsOptions
	DeleteCommentOptions
	UpdateCommentOptions
	Annotation
	AnnotationRange
	ListAnnotationsOptions
	GetCommentOptions
	LikeCommentOptions
	LawSet
	Author
	Law
	Branch
	Version
	CreateLawOptions
	CreateLawsOptions
	CreateLawRequest
	CreateLawReply
	DeleteLawOptions
	DeleteLawRequest
	DeleteLawReply
	DiffLawsOptions
	DiffLawsRequest
	DiffLawsReply
	GetLawOptions
	GetLawRequest
	GetLawReply
	ListLawsOptions
	ListLawsRequest
	ListLawsReply
	UpdateLawOptions
	UpdateLawRequest
	UpdateLawReply
	Upstream
	UpstreamMetadata
	CreateUpstreamRequest
	CreateUpstreamReply
	GetUpstreamRequest
	GetUpstreamReply
	ListUpstreamsRequest
	ListUpstreamsReply
	UpdateUpstreamRequest
	UpdateUpstreamReply
	User
	UserMetadata
	GetUserOptions
	GetUserRequest
	GetUserReply
	CreateUserRequest
	CreateUserReply
	ListUsersOptions
	ListUsersRequest
	ListUsersReply
	RegisterUserRequest
	RegisterUserReply
	UpdateUserOptions
	UpdateUserRequest
	UpdateUserReply
	UploadAvatarOptions
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type SaveReposOptions_RequestType int32

const (
	SaveReposOptions_SAVE SaveReposOptions_RequestType = 0
	SaveReposOptions_LOAD SaveReposOptions_RequestType = 1
)

var SaveReposOptions_RequestType_name = map[int32]string{
	0: "SAVE",
	1: "LOAD",
}
var SaveReposOptions_RequestType_value = map[string]int32{
	"SAVE": 0,
	"LOAD": 1,
}

func (x SaveReposOptions_RequestType) String() string {
	return proto1.EnumName(SaveReposOptions_RequestType_name, int32(x))
}
func (SaveReposOptions_RequestType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{3, 0}
}

type ServerStats struct {
	Upstreams string `protobuf:"bytes,1,opt,name=upstreams" json:"upstreams,omitempty"`
	Users     string `protobuf:"bytes,2,opt,name=users" json:"users,omitempty"`
	Laws      string `protobuf:"bytes,3,opt,name=laws" json:"laws,omitempty"`
	Branches  string `protobuf:"bytes,4,opt,name=branches" json:"branches,omitempty"`
	Versions  string `protobuf:"bytes,5,opt,name=versions" json:"versions,omitempty"`
	Votes     string `protobuf:"bytes,6,opt,name=votes" json:"votes,omitempty"`
}

func (m *ServerStats) Reset()                    { *m = ServerStats{} }
func (m *ServerStats) String() string            { return proto1.CompactTextString(m) }
func (*ServerStats) ProtoMessage()               {}
func (*ServerStats) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ServerStats) GetUpstreams() string {
	if m != nil {
		return m.Upstreams
	}
	return ""
}

func (m *ServerStats) GetUsers() string {
	if m != nil {
		return m.Users
	}
	return ""
}

func (m *ServerStats) GetLaws() string {
	if m != nil {
		return m.Laws
	}
	return ""
}

func (m *ServerStats) GetBranches() string {
	if m != nil {
		return m.Branches
	}
	return ""
}

func (m *ServerStats) GetVersions() string {
	if m != nil {
		return m.Versions
	}
	return ""
}

func (m *ServerStats) GetVotes() string {
	if m != nil {
		return m.Votes
	}
	return ""
}

type LoadReposOptions struct {
}

func (m *LoadReposOptions) Reset()                    { *m = LoadReposOptions{} }
func (m *LoadReposOptions) String() string            { return proto1.CompactTextString(m) }
func (*LoadReposOptions) ProtoMessage()               {}
func (*LoadReposOptions) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type LoadReposReply struct {
}

func (m *LoadReposReply) Reset()                    { *m = LoadReposReply{} }
func (m *LoadReposReply) String() string            { return proto1.CompactTextString(m) }
func (*LoadReposReply) ProtoMessage()               {}
func (*LoadReposReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type SaveReposOptions struct {
	ReqType SaveReposOptions_RequestType `protobuf:"varint,1,opt,name=req_type,json=reqType,enum=proto.SaveReposOptions_RequestType" json:"req_type,omitempty"`
}

func (m *SaveReposOptions) Reset()                    { *m = SaveReposOptions{} }
func (m *SaveReposOptions) String() string            { return proto1.CompactTextString(m) }
func (*SaveReposOptions) ProtoMessage()               {}
func (*SaveReposOptions) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SaveReposOptions) GetReqType() SaveReposOptions_RequestType {
	if m != nil {
		return m.ReqType
	}
	return SaveReposOptions_SAVE
}

type SaveReposReply struct {
}

func (m *SaveReposReply) Reset()                    { *m = SaveReposReply{} }
func (m *SaveReposReply) String() string            { return proto1.CompactTextString(m) }
func (*SaveReposReply) ProtoMessage()               {}
func (*SaveReposReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func init() {
	proto1.RegisterType((*ServerStats)(nil), "proto.ServerStats")
	proto1.RegisterType((*LoadReposOptions)(nil), "proto.LoadReposOptions")
	proto1.RegisterType((*LoadReposReply)(nil), "proto.LoadReposReply")
	proto1.RegisterType((*SaveReposOptions)(nil), "proto.SaveReposOptions")
	proto1.RegisterType((*SaveReposReply)(nil), "proto.SaveReposReply")
	proto1.RegisterEnum("proto.SaveReposOptions_RequestType", SaveReposOptions_RequestType_name, SaveReposOptions_RequestType_value)
}

func init() { proto1.RegisterFile("proto/admin.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 259 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0xc6, 0xad, 0xb6, 0xb3, 0x7b, 0x83, 0x51, 0x83, 0x87, 0x20, 0x1e, 0x34, 0x5e, 0x3c, 0x55,
	0xd0, 0xbb, 0x30, 0xd0, 0xdb, 0x60, 0x90, 0x8a, 0x57, 0xc9, 0xdc, 0x03, 0x07, 0x5b, 0x93, 0xe6,
	0xa5, 0x95, 0xfe, 0x3d, 0xfe, 0xa3, 0x92, 0x57, 0xac, 0x63, 0xa7, 0x7c, 0xdf, 0xef, 0x7d, 0xe4,
	0x7b, 0x09, 0x5c, 0x38, 0x6f, 0x83, 0x7d, 0x30, 0x9b, 0xfd, 0xb6, 0x2e, 0x59, 0x8b, 0x8c, 0x0f,
	0xf5, 0x93, 0xc0, 0xac, 0x42, 0xdf, 0xa1, 0xaf, 0x82, 0x09, 0x24, 0xae, 0x61, 0xda, 0x3a, 0x0a,
	0x1e, 0xcd, 0x9e, 0x64, 0x72, 0x93, 0xdc, 0x4f, 0xf5, 0x3f, 0x10, 0x97, 0x90, 0xb5, 0x84, 0x9e,
	0xe4, 0x29, 0x4f, 0x06, 0x23, 0x04, 0xa4, 0x3b, 0xf3, 0x4d, 0xf2, 0x8c, 0x21, 0x6b, 0x71, 0x05,
	0xf9, 0xda, 0x9b, 0xfa, 0xf3, 0x0b, 0x49, 0xa6, 0xcc, 0x47, 0x1f, 0x67, 0x1d, 0x7a, 0xda, 0xda,
	0x9a, 0x64, 0x36, 0xcc, 0xfe, 0x7c, 0x6c, 0xe8, 0x6c, 0x40, 0x92, 0x93, 0xa1, 0x81, 0x8d, 0x12,
	0x50, 0x2c, 0xad, 0xd9, 0x68, 0x74, 0x96, 0x56, 0x2e, 0xc4, 0xa4, 0x2a, 0x60, 0x3e, 0x32, 0x8d,
	0x6e, 0xd7, 0xab, 0x16, 0x8a, 0xca, 0x74, 0x78, 0x98, 0x12, 0xcf, 0x90, 0x7b, 0x6c, 0x3e, 0x42,
	0xef, 0x90, 0x9f, 0x33, 0x7f, 0xbc, 0x1b, 0x3e, 0xa0, 0x3c, 0x8e, 0x96, 0x1a, 0x9b, 0x16, 0x29,
	0xbc, 0xf5, 0x0e, 0xf5, 0xb9, 0xc7, 0x26, 0x0a, 0x75, 0x0b, 0xb3, 0x03, 0x2e, 0x72, 0x48, 0xab,
	0xc5, 0xfb, 0x6b, 0x71, 0x12, 0xd5, 0x72, 0xb5, 0x78, 0x29, 0x92, 0xb8, 0xc8, 0x78, 0x17, 0x2f,
	0xb2, 0x9e, 0x70, 0xc3, 0xd3, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xef, 0xa1, 0x3d, 0xef, 0x77,
	0x01, 0x00, 0x00,
}
