// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/comments.proto

package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ListCommentsOptions_RequestType int32

const (
	ListCommentsOptions_BY_USERNAME ListCommentsOptions_RequestType = 0
	ListCommentsOptions_BY_VERSION  ListCommentsOptions_RequestType = 1
)

var ListCommentsOptions_RequestType_name = map[int32]string{
	0: "BY_USERNAME",
	1: "BY_VERSION",
}
var ListCommentsOptions_RequestType_value = map[string]int32{
	"BY_USERNAME": 0,
	"BY_VERSION":  1,
}

func (x ListCommentsOptions_RequestType) String() string {
	return proto1.EnumName(ListCommentsOptions_RequestType_name, int32(x))
}
func (ListCommentsOptions_RequestType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor3, []int{1, 0}
}

type ListAnnotationsOptions_RequestType int32

const (
	ListAnnotationsOptions_BY_USERNAME ListAnnotationsOptions_RequestType = 0
	ListAnnotationsOptions_BY_UID      ListAnnotationsOptions_RequestType = 1
	ListAnnotationsOptions_BY_COMMENT  ListAnnotationsOptions_RequestType = 2
)

var ListAnnotationsOptions_RequestType_name = map[int32]string{
	0: "BY_USERNAME",
	1: "BY_UID",
	2: "BY_COMMENT",
}
var ListAnnotationsOptions_RequestType_value = map[string]int32{
	"BY_USERNAME": 0,
	"BY_UID":      1,
	"BY_COMMENT":  2,
}

func (x ListAnnotationsOptions_RequestType) String() string {
	return proto1.EnumName(ListAnnotationsOptions_RequestType_name, int32(x))
}
func (ListAnnotationsOptions_RequestType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor3, []int{6, 0}
}

type GetCommentOptions_RequestType int32

const (
	GetCommentOptions_BY_USER_VERSION GetCommentOptions_RequestType = 0
	GetCommentOptions_BY_UID          GetCommentOptions_RequestType = 1
)

var GetCommentOptions_RequestType_name = map[int32]string{
	0: "BY_USER_VERSION",
	1: "BY_UID",
}
var GetCommentOptions_RequestType_value = map[string]int32{
	"BY_USER_VERSION": 0,
	"BY_UID":          1,
}

func (x GetCommentOptions_RequestType) String() string {
	return proto1.EnumName(GetCommentOptions_RequestType_name, int32(x))
}
func (GetCommentOptions_RequestType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor3, []int{7, 0}
}

type Comment struct {
	Comment         string        `protobuf:"bytes,1,opt,name=comment" json:"comment,omitempty"`
	Username        string        `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	UserId          string        `protobuf:"bytes,3,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	AnnotationCount int32         `protobuf:"varint,4,opt,name=annotation_count,json=annotationCount" json:"annotation_count,omitempty"`
	Annotations     []*Annotation `protobuf:"bytes,5,rep,name=annotations" json:"annotations,omitempty"`
	Upstream        string        `protobuf:"bytes,6,opt,name=upstream" json:"upstream,omitempty"`
	Ident           string        `protobuf:"bytes,7,opt,name=ident" json:"ident,omitempty"`
	Branch          string        `protobuf:"bytes,8,opt,name=branch" json:"branch,omitempty"`
	Version         uint32        `protobuf:"varint,9,opt,name=version" json:"version,omitempty"`
	Uid             string        `protobuf:"bytes,10,opt,name=uid" json:"uid,omitempty"`
	Disabled        bool          `protobuf:"varint,11,opt,name=disabled" json:"disabled,omitempty"`
	User            *User         `protobuf:"bytes,12,opt,name=user" json:"user,omitempty"`
	Likes           int32         `protobuf:"varint,13,opt,name=likes" json:"likes,omitempty"`
	Liked           bool          `protobuf:"varint,14,opt,name=liked" json:"liked,omitempty"`
}

func (m *Comment) Reset()                    { *m = Comment{} }
func (m *Comment) String() string            { return proto1.CompactTextString(m) }
func (*Comment) ProtoMessage()               {}
func (*Comment) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

func (m *Comment) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *Comment) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Comment) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Comment) GetAnnotationCount() int32 {
	if m != nil {
		return m.AnnotationCount
	}
	return 0
}

func (m *Comment) GetAnnotations() []*Annotation {
	if m != nil {
		return m.Annotations
	}
	return nil
}

func (m *Comment) GetUpstream() string {
	if m != nil {
		return m.Upstream
	}
	return ""
}

func (m *Comment) GetIdent() string {
	if m != nil {
		return m.Ident
	}
	return ""
}

func (m *Comment) GetBranch() string {
	if m != nil {
		return m.Branch
	}
	return ""
}

func (m *Comment) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Comment) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *Comment) GetDisabled() bool {
	if m != nil {
		return m.Disabled
	}
	return false
}

func (m *Comment) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Comment) GetLikes() int32 {
	if m != nil {
		return m.Likes
	}
	return 0
}

func (m *Comment) GetLiked() bool {
	if m != nil {
		return m.Liked
	}
	return false
}

type ListCommentsOptions struct {
	ReqType  ListCommentsOptions_RequestType `protobuf:"varint,1,opt,name=req_type,json=reqType,enum=proto.ListCommentsOptions_RequestType" json:"req_type,omitempty"`
	Upstream string                          `protobuf:"bytes,2,opt,name=upstream" json:"upstream,omitempty"`
	Ident    string                          `protobuf:"bytes,3,opt,name=ident" json:"ident,omitempty"`
	Branch   string                          `protobuf:"bytes,4,opt,name=branch" json:"branch,omitempty"`
	Version  int32                           `protobuf:"varint,5,opt,name=version" json:"version,omitempty"`
	Filter   string                          `protobuf:"bytes,6,opt,name=filter" json:"filter,omitempty"`
	PageSize int32                           `protobuf:"varint,7,opt,name=page_size,json=pageSize" json:"page_size,omitempty"`
	PageNum  int32                           `protobuf:"varint,8,opt,name=page_num,json=pageNum" json:"page_num,omitempty"`
	Desc     bool                            `protobuf:"varint,9,opt,name=desc" json:"desc,omitempty"`
	Username string                          `protobuf:"bytes,10,opt,name=username" json:"username,omitempty"`
	OrderBy  string                          `protobuf:"bytes,11,opt,name=order_by,json=orderBy" json:"order_by,omitempty"`
}

func (m *ListCommentsOptions) Reset()                    { *m = ListCommentsOptions{} }
func (m *ListCommentsOptions) String() string            { return proto1.CompactTextString(m) }
func (*ListCommentsOptions) ProtoMessage()               {}
func (*ListCommentsOptions) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

func (m *ListCommentsOptions) GetReqType() ListCommentsOptions_RequestType {
	if m != nil {
		return m.ReqType
	}
	return ListCommentsOptions_BY_USERNAME
}

func (m *ListCommentsOptions) GetUpstream() string {
	if m != nil {
		return m.Upstream
	}
	return ""
}

func (m *ListCommentsOptions) GetIdent() string {
	if m != nil {
		return m.Ident
	}
	return ""
}

func (m *ListCommentsOptions) GetBranch() string {
	if m != nil {
		return m.Branch
	}
	return ""
}

func (m *ListCommentsOptions) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *ListCommentsOptions) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

func (m *ListCommentsOptions) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListCommentsOptions) GetPageNum() int32 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

func (m *ListCommentsOptions) GetDesc() bool {
	if m != nil {
		return m.Desc
	}
	return false
}

func (m *ListCommentsOptions) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ListCommentsOptions) GetOrderBy() string {
	if m != nil {
		return m.OrderBy
	}
	return ""
}

type DeleteCommentOptions struct {
}

func (m *DeleteCommentOptions) Reset()                    { *m = DeleteCommentOptions{} }
func (m *DeleteCommentOptions) String() string            { return proto1.CompactTextString(m) }
func (*DeleteCommentOptions) ProtoMessage()               {}
func (*DeleteCommentOptions) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{2} }

type UpdateCommentOptions struct {
}

func (m *UpdateCommentOptions) Reset()                    { *m = UpdateCommentOptions{} }
func (m *UpdateCommentOptions) String() string            { return proto1.CompactTextString(m) }
func (*UpdateCommentOptions) ProtoMessage()               {}
func (*UpdateCommentOptions) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{3} }

type Annotation struct {
	Quote     string             `protobuf:"bytes,1,opt,name=quote" json:"quote,omitempty"`
	Ranges    []*AnnotationRange `protobuf:"bytes,2,rep,name=ranges" json:"ranges,omitempty"`
	Text      string             `protobuf:"bytes,3,opt,name=text" json:"text,omitempty"`
	Upstream  string             `protobuf:"bytes,4,opt,name=upstream" json:"upstream,omitempty"`
	Ident     string             `protobuf:"bytes,5,opt,name=ident" json:"ident,omitempty"`
	Branch    string             `protobuf:"bytes,6,opt,name=branch" json:"branch,omitempty"`
	Version   string             `protobuf:"bytes,7,opt,name=version" json:"version,omitempty"`
	Id        string             `protobuf:"bytes,8,opt,name=id" json:"id,omitempty"`
	CommentId string             `protobuf:"bytes,9,opt,name=comment_id,json=commentId" json:"comment_id,omitempty"`
}

func (m *Annotation) Reset()                    { *m = Annotation{} }
func (m *Annotation) String() string            { return proto1.CompactTextString(m) }
func (*Annotation) ProtoMessage()               {}
func (*Annotation) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{4} }

func (m *Annotation) GetQuote() string {
	if m != nil {
		return m.Quote
	}
	return ""
}

func (m *Annotation) GetRanges() []*AnnotationRange {
	if m != nil {
		return m.Ranges
	}
	return nil
}

func (m *Annotation) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Annotation) GetUpstream() string {
	if m != nil {
		return m.Upstream
	}
	return ""
}

func (m *Annotation) GetIdent() string {
	if m != nil {
		return m.Ident
	}
	return ""
}

func (m *Annotation) GetBranch() string {
	if m != nil {
		return m.Branch
	}
	return ""
}

func (m *Annotation) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Annotation) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Annotation) GetCommentId() string {
	if m != nil {
		return m.CommentId
	}
	return ""
}

type AnnotationRange struct {
	Start       string `protobuf:"bytes,1,opt,name=start" json:"start,omitempty"`
	StartOffset int32  `protobuf:"varint,2,opt,name=startOffset" json:"startOffset,omitempty"`
	End         string `protobuf:"bytes,3,opt,name=end" json:"end,omitempty"`
	EndOffset   int32  `protobuf:"varint,4,opt,name=endOffset" json:"endOffset,omitempty"`
}

func (m *AnnotationRange) Reset()                    { *m = AnnotationRange{} }
func (m *AnnotationRange) String() string            { return proto1.CompactTextString(m) }
func (*AnnotationRange) ProtoMessage()               {}
func (*AnnotationRange) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{5} }

func (m *AnnotationRange) GetStart() string {
	if m != nil {
		return m.Start
	}
	return ""
}

func (m *AnnotationRange) GetStartOffset() int32 {
	if m != nil {
		return m.StartOffset
	}
	return 0
}

func (m *AnnotationRange) GetEnd() string {
	if m != nil {
		return m.End
	}
	return ""
}

func (m *AnnotationRange) GetEndOffset() int32 {
	if m != nil {
		return m.EndOffset
	}
	return 0
}

type ListAnnotationsOptions struct {
	ReqType   ListAnnotationsOptions_RequestType `protobuf:"varint,1,opt,name=req_type,json=reqType,enum=proto.ListAnnotationsOptions_RequestType" json:"req_type,omitempty"`
	Username  string                             `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	Uid       string                             `protobuf:"bytes,3,opt,name=uid" json:"uid,omitempty"`
	CommentId string                             `protobuf:"bytes,4,opt,name=comment_id,json=commentId" json:"comment_id,omitempty"`
}

func (m *ListAnnotationsOptions) Reset()                    { *m = ListAnnotationsOptions{} }
func (m *ListAnnotationsOptions) String() string            { return proto1.CompactTextString(m) }
func (*ListAnnotationsOptions) ProtoMessage()               {}
func (*ListAnnotationsOptions) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{6} }

func (m *ListAnnotationsOptions) GetReqType() ListAnnotationsOptions_RequestType {
	if m != nil {
		return m.ReqType
	}
	return ListAnnotationsOptions_BY_USERNAME
}

func (m *ListAnnotationsOptions) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ListAnnotationsOptions) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ListAnnotationsOptions) GetCommentId() string {
	if m != nil {
		return m.CommentId
	}
	return ""
}

type GetCommentOptions struct {
	ReqType  GetCommentOptions_RequestType `protobuf:"varint,1,opt,name=req_type,json=reqType,enum=proto.GetCommentOptions_RequestType" json:"req_type,omitempty"`
	Uid      string                        `protobuf:"bytes,2,opt,name=uid" json:"uid,omitempty"`
	Upstream string                        `protobuf:"bytes,3,opt,name=upstream" json:"upstream,omitempty"`
	Ident    string                        `protobuf:"bytes,4,opt,name=ident" json:"ident,omitempty"`
	Branch   string                        `protobuf:"bytes,5,opt,name=branch" json:"branch,omitempty"`
	Version  int32                         `protobuf:"varint,6,opt,name=version" json:"version,omitempty"`
	Username string                        `protobuf:"bytes,7,opt,name=username" json:"username,omitempty"`
	Quiet    bool                          `protobuf:"varint,8,opt,name=quiet" json:"quiet,omitempty"`
}

func (m *GetCommentOptions) Reset()                    { *m = GetCommentOptions{} }
func (m *GetCommentOptions) String() string            { return proto1.CompactTextString(m) }
func (*GetCommentOptions) ProtoMessage()               {}
func (*GetCommentOptions) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{7} }

func (m *GetCommentOptions) GetReqType() GetCommentOptions_RequestType {
	if m != nil {
		return m.ReqType
	}
	return GetCommentOptions_BY_USER_VERSION
}

func (m *GetCommentOptions) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *GetCommentOptions) GetUpstream() string {
	if m != nil {
		return m.Upstream
	}
	return ""
}

func (m *GetCommentOptions) GetIdent() string {
	if m != nil {
		return m.Ident
	}
	return ""
}

func (m *GetCommentOptions) GetBranch() string {
	if m != nil {
		return m.Branch
	}
	return ""
}

func (m *GetCommentOptions) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *GetCommentOptions) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *GetCommentOptions) GetQuiet() bool {
	if m != nil {
		return m.Quiet
	}
	return false
}

type LikeCommentOptions struct {
	CommentId string `protobuf:"bytes,1,opt,name=comment_id,json=commentId" json:"comment_id,omitempty"`
	Username  string `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
}

func (m *LikeCommentOptions) Reset()                    { *m = LikeCommentOptions{} }
func (m *LikeCommentOptions) String() string            { return proto1.CompactTextString(m) }
func (*LikeCommentOptions) ProtoMessage()               {}
func (*LikeCommentOptions) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{8} }

func (m *LikeCommentOptions) GetCommentId() string {
	if m != nil {
		return m.CommentId
	}
	return ""
}

func (m *LikeCommentOptions) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func init() {
	proto1.RegisterType((*Comment)(nil), "proto.Comment")
	proto1.RegisterType((*ListCommentsOptions)(nil), "proto.ListCommentsOptions")
	proto1.RegisterType((*DeleteCommentOptions)(nil), "proto.DeleteCommentOptions")
	proto1.RegisterType((*UpdateCommentOptions)(nil), "proto.UpdateCommentOptions")
	proto1.RegisterType((*Annotation)(nil), "proto.Annotation")
	proto1.RegisterType((*AnnotationRange)(nil), "proto.AnnotationRange")
	proto1.RegisterType((*ListAnnotationsOptions)(nil), "proto.ListAnnotationsOptions")
	proto1.RegisterType((*GetCommentOptions)(nil), "proto.GetCommentOptions")
	proto1.RegisterType((*LikeCommentOptions)(nil), "proto.LikeCommentOptions")
	proto1.RegisterEnum("proto.ListCommentsOptions_RequestType", ListCommentsOptions_RequestType_name, ListCommentsOptions_RequestType_value)
	proto1.RegisterEnum("proto.ListAnnotationsOptions_RequestType", ListAnnotationsOptions_RequestType_name, ListAnnotationsOptions_RequestType_value)
	proto1.RegisterEnum("proto.GetCommentOptions_RequestType", GetCommentOptions_RequestType_name, GetCommentOptions_RequestType_value)
}

func init() { proto1.RegisterFile("proto/comments.proto", fileDescriptor3) }

var fileDescriptor3 = []byte{
	// 776 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0xdd, 0x6e, 0xea, 0x46,
	0x10, 0xae, 0x6d, 0xfc, 0xc3, 0xb8, 0x07, 0x38, 0x7b, 0x22, 0xea, 0xa4, 0xad, 0x8a, 0xac, 0xaa,
	0x22, 0x37, 0x54, 0x4a, 0xee, 0x7a, 0x53, 0xe5, 0x07, 0x55, 0x48, 0x09, 0x48, 0x9b, 0xa4, 0x52,
	0xae, 0x2c, 0x83, 0x27, 0xa9, 0x15, 0xb0, 0xc1, 0xbb, 0x54, 0x25, 0x2f, 0xd0, 0x47, 0xe8, 0x4b,
	0xf4, 0xbd, 0xfa, 0x0c, 0xbd, 0xab, 0x76, 0xbd, 0x18, 0x6c, 0x70, 0xcf, 0x15, 0xf3, 0xcd, 0xec,
	0xe2, 0x9d, 0xef, 0x9b, 0x6f, 0xe0, 0x64, 0x99, 0xa5, 0x3c, 0xfd, 0x71, 0x96, 0x2e, 0x16, 0x98,
	0x70, 0x36, 0x90, 0x90, 0x98, 0xf2, 0xe7, 0xac, 0x93, 0x17, 0xd7, 0x0c, 0xb3, 0xbc, 0xe0, 0xff,
	0x65, 0x80, 0x7d, 0x93, 0x9f, 0x25, 0x1e, 0xd8, 0xea, 0x9a, 0xa7, 0xf5, 0xb4, 0x7e, 0x93, 0x6e,
	0x21, 0x39, 0x03, 0x47, 0xdc, 0x49, 0xc2, 0x05, 0x7a, 0xba, 0x2c, 0x15, 0x98, 0x7c, 0x05, 0xb6,
	0x88, 0x83, 0x38, 0xf2, 0x0c, 0x59, 0xb2, 0x04, 0x1c, 0x45, 0xe4, 0x1c, 0x3a, 0x61, 0x92, 0xa4,
	0x3c, 0xe4, 0x71, 0x9a, 0x04, 0xb3, 0x74, 0x9d, 0x70, 0xaf, 0xd1, 0xd3, 0xfa, 0x26, 0x6d, 0xef,
	0xf2, 0x37, 0x22, 0x4d, 0x2e, 0xc1, 0xdd, 0xa5, 0x98, 0x67, 0xf6, 0x8c, 0xbe, 0x7b, 0xf1, 0x31,
	0x7f, 0xe2, 0xe0, 0xaa, 0xa8, 0xd0, 0xfd, 0x53, 0xf2, 0x51, 0x4b, 0xc6, 0x33, 0x0c, 0x17, 0x9e,
	0xa5, 0x1e, 0xa5, 0x30, 0x39, 0x01, 0x33, 0x8e, 0x44, 0x23, 0xb6, 0x2c, 0xe4, 0x80, 0x74, 0xc1,
	0x9a, 0x66, 0x61, 0x32, 0xfb, 0xcd, 0x73, 0xf2, 0x97, 0xe6, 0x48, 0x34, 0xfe, 0x3b, 0x66, 0x2c,
	0x4e, 0x13, 0xaf, 0xd9, 0xd3, 0xfa, 0x1f, 0xe8, 0x16, 0x92, 0x0e, 0x18, 0xeb, 0x38, 0xf2, 0x40,
	0x1e, 0x17, 0xa1, 0xf8, 0x6a, 0x14, 0xb3, 0x70, 0x3a, 0xc7, 0xc8, 0x73, 0x7b, 0x5a, 0xdf, 0xa1,
	0x05, 0x26, 0xdf, 0x41, 0x43, 0xf4, 0xee, 0x7d, 0xd9, 0xd3, 0xfa, 0xee, 0x85, 0xab, 0xde, 0xff,
	0xc4, 0x30, 0xa3, 0xb2, 0x20, 0x9e, 0x35, 0x8f, 0xdf, 0x90, 0x79, 0x1f, 0x24, 0x0f, 0x39, 0xd8,
	0x66, 0x23, 0xaf, 0x25, 0xff, 0x2f, 0x07, 0xfe, 0x9f, 0x06, 0x7c, 0xba, 0x8b, 0x19, 0x57, 0xea,
	0xb0, 0xc9, 0x32, 0x6f, 0xfb, 0x0a, 0x9c, 0x0c, 0x57, 0x01, 0xdf, 0x2c, 0x51, 0xca, 0xd4, 0xba,
	0xf8, 0x41, 0x7d, 0xe8, 0xc8, 0xe9, 0x01, 0xc5, 0xd5, 0x1a, 0x19, 0x7f, 0xdc, 0x2c, 0x91, 0xda,
	0x19, 0xae, 0x44, 0x50, 0x62, 0x4e, 0xaf, 0x63, 0xce, 0x38, 0xce, 0x5c, 0xa3, 0x8e, 0x39, 0x53,
	0xb6, 0x54, 0x30, 0xd7, 0x05, 0xeb, 0x25, 0x9e, 0x73, 0xcc, 0x94, 0x36, 0x0a, 0x91, 0xaf, 0xa1,
	0xb9, 0x0c, 0x5f, 0x31, 0x60, 0xf1, 0x3b, 0x4a, 0x75, 0x4c, 0xea, 0x88, 0xc4, 0x43, 0xfc, 0x8e,
	0xe4, 0x14, 0x64, 0x1c, 0x24, 0xeb, 0x85, 0x94, 0xc8, 0xa4, 0xb6, 0xc0, 0xe3, 0xf5, 0x82, 0x10,
	0x68, 0x44, 0xc8, 0x66, 0x52, 0x20, 0x87, 0xca, 0xb8, 0x34, 0x96, 0x50, 0x19, 0xcb, 0x53, 0x70,
	0xd2, 0x2c, 0xc2, 0x2c, 0x98, 0x6e, 0xa4, 0x4e, 0x4d, 0x6a, 0x4b, 0x7c, 0xbd, 0xf1, 0x07, 0xe0,
	0xee, 0xd1, 0x42, 0xda, 0xe0, 0x5e, 0x3f, 0x07, 0x4f, 0x0f, 0x43, 0x3a, 0xbe, 0xba, 0x1f, 0x76,
	0xbe, 0x20, 0x2d, 0x80, 0xeb, 0xe7, 0xe0, 0xd7, 0x21, 0x7d, 0x18, 0x4d, 0xc6, 0x1d, 0xcd, 0xef,
	0xc2, 0xc9, 0x2d, 0xce, 0x91, 0xa3, 0x22, 0x57, 0x71, 0x2b, 0xf2, 0x4f, 0xcb, 0x28, 0x3c, 0xc8,
	0xff, 0xab, 0x01, 0xec, 0x86, 0x56, 0x30, 0xba, 0x5a, 0xa7, 0x1c, 0x95, 0xa9, 0x72, 0x40, 0x06,
	0x60, 0x65, 0x61, 0xf2, 0x8a, 0xcc, 0xd3, 0xe5, 0xb4, 0x77, 0x0f, 0xa7, 0x5d, 0x94, 0xa9, 0x3a,
	0x25, 0xfa, 0xe7, 0xf8, 0xc7, 0x56, 0x16, 0x19, 0x97, 0x74, 0x6c, 0xd4, 0xe9, 0x68, 0x1e, 0xd7,
	0xd1, 0xaa, 0xd3, 0x31, 0x77, 0x4c, 0xa1, 0x63, 0x0b, 0xf4, 0x38, 0x52, 0x7e, 0xd1, 0xe3, 0x88,
	0x7c, 0x0b, 0xa0, 0xb6, 0x82, 0x70, 0x7c, 0x53, 0xe6, 0x9b, 0x2a, 0x33, 0x8a, 0xfc, 0x0d, 0xb4,
	0x2b, 0x1d, 0x88, 0x97, 0x30, 0x1e, 0x66, 0xdb, 0xa5, 0x92, 0x03, 0xd2, 0x03, 0x57, 0x06, 0x93,
	0x97, 0x17, 0x86, 0x5c, 0x8e, 0xa1, 0x49, 0xf7, 0x53, 0xc2, 0x7b, 0x98, 0x6c, 0x97, 0x8a, 0x08,
	0xc9, 0x37, 0xd0, 0xc4, 0x24, 0x52, 0x37, 0xf2, 0x55, 0xb2, 0x4b, 0xf8, 0xff, 0x68, 0xd0, 0x15,
	0x16, 0xd8, 0x7d, 0xbf, 0xf0, 0xcc, 0xed, 0x81, 0x67, 0xce, 0xf7, 0x3c, 0x73, 0x78, 0xa1, 0xde,
	0x36, 0x75, 0x5b, 0x50, 0x2d, 0x0a, 0x63, 0xb7, 0x28, 0xca, 0x44, 0x35, 0xaa, 0x44, 0xfd, 0xf4,
	0x99, 0x21, 0x04, 0xb0, 0x44, 0x62, 0x74, 0xdb, 0xd1, 0xd4, 0x40, 0xde, 0x4c, 0xee, 0xef, 0x87,
	0xe3, 0xc7, 0x8e, 0xee, 0xff, 0xad, 0xc3, 0xc7, 0x5f, 0x90, 0x97, 0xc7, 0x8e, 0xfc, 0x7c, 0xd0,
	0xe4, 0xf7, 0xaa, 0xc9, 0x83, 0xb3, 0xc7, 0xfb, 0x53, 0x3d, 0xe8, 0xa5, 0x65, 0x57, 0x0c, 0x98,
	0x51, 0x37, 0x60, 0x8d, 0xe3, 0x03, 0x66, 0xd6, 0x0d, 0x98, 0x55, 0x5e, 0x14, 0xfb, 0xac, 0xda,
	0x15, 0x56, 0xa5, 0x75, 0x62, 0xe4, 0x72, 0xfe, 0x1c, 0x9a, 0x83, 0xaa, 0x7f, 0x3f, 0x41, 0x5b,
	0x51, 0x57, 0x78, 0xb6, 0x44, 0x9f, 0x3f, 0x01, 0x72, 0x17, 0xbf, 0x55, 0x5c, 0x5a, 0xd1, 0x47,
	0xab, 0xe8, 0xf3, 0x7f, 0x62, 0x4f, 0x2d, 0x49, 0xeb, 0xe5, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff,
	0xf4, 0xb5, 0xfc, 0x4c, 0x6c, 0x07, 0x00, 0x00,
}
