// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/law.proto

package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ListLawsOptions_RequestType int32

const (
	ListLawsOptions_USER_LAWS       ListLawsOptions_RequestType = 0
	ListLawsOptions_UPSTREAM_LAWS   ListLawsOptions_RequestType = 1
	ListLawsOptions_SEARCH          ListLawsOptions_RequestType = 2
	ListLawsOptions_LAW_BRANCHES    ListLawsOptions_RequestType = 3
	ListLawsOptions_BRANCH_VERSIONS ListLawsOptions_RequestType = 4
)

var ListLawsOptions_RequestType_name = map[int32]string{
	0: "USER_LAWS",
	1: "UPSTREAM_LAWS",
	2: "SEARCH",
	3: "LAW_BRANCHES",
	4: "BRANCH_VERSIONS",
}
var ListLawsOptions_RequestType_value = map[string]int32{
	"USER_LAWS":       0,
	"UPSTREAM_LAWS":   1,
	"SEARCH":          2,
	"LAW_BRANCHES":    3,
	"BRANCH_VERSIONS": 4,
}

func (x ListLawsOptions_RequestType) String() string {
	return proto1.EnumName(ListLawsOptions_RequestType_name, int32(x))
}
func (ListLawsOptions_RequestType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor4, []int{18, 0}
}

type LawSet struct {
	Law     *Law     `protobuf:"bytes,1,opt,name=law" json:"law,omitempty"`
	Branch  *Branch  `protobuf:"bytes,2,opt,name=branch" json:"branch,omitempty"`
	Version *Version `protobuf:"bytes,3,opt,name=version" json:"version,omitempty"`
	Author  *Author  `protobuf:"bytes,4,opt,name=author" json:"author,omitempty"`
	User    *User    `protobuf:"bytes,5,opt,name=user" json:"user,omitempty"`
}

func (m *LawSet) Reset()                    { *m = LawSet{} }
func (m *LawSet) String() string            { return proto1.CompactTextString(m) }
func (*LawSet) ProtoMessage()               {}
func (*LawSet) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{0} }

func (m *LawSet) GetLaw() *Law {
	if m != nil {
		return m.Law
	}
	return nil
}

func (m *LawSet) GetBranch() *Branch {
	if m != nil {
		return m.Branch
	}
	return nil
}

func (m *LawSet) GetVersion() *Version {
	if m != nil {
		return m.Version
	}
	return nil
}

func (m *LawSet) GetAuthor() *Author {
	if m != nil {
		return m.Author
	}
	return nil
}

func (m *LawSet) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type Author struct {
	Uid        string `protobuf:"bytes,1,opt,name=uid" json:"uid,omitempty"`
	Username   string `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	Email      string `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
	FullName   string `protobuf:"bytes,4,opt,name=full_name,json=fullName" json:"full_name,omitempty"`
	PictureUrl string `protobuf:"bytes,5,opt,name=picture_url,json=pictureUrl" json:"picture_url,omitempty"`
}

func (m *Author) Reset()                    { *m = Author{} }
func (m *Author) String() string            { return proto1.CompactTextString(m) }
func (*Author) ProtoMessage()               {}
func (*Author) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{1} }

func (m *Author) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *Author) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Author) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Author) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *Author) GetPictureUrl() string {
	if m != nil {
		return m.PictureUrl
	}
	return ""
}

type Law struct {
	Uid         string `protobuf:"bytes,1,opt,name=uid" json:"uid,omitempty"`
	UserId      string `protobuf:"bytes,2,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	Upstream    string `protobuf:"bytes,3,opt,name=upstream" json:"upstream,omitempty"`
	Ident       string `protobuf:"bytes,4,opt,name=ident" json:"ident,omitempty"`
	Title       string `protobuf:"bytes,5,opt,name=title" json:"title,omitempty"`
	ShortTitle  string `protobuf:"bytes,6,opt,name=short_title,json=shortTitle" json:"short_title,omitempty"`
	Description string `protobuf:"bytes,7,opt,name=description" json:"description,omitempty"`
	Url         string `protobuf:"bytes,8,opt,name=url" json:"url,omitempty"`
}

func (m *Law) Reset()                    { *m = Law{} }
func (m *Law) String() string            { return proto1.CompactTextString(m) }
func (*Law) ProtoMessage()               {}
func (*Law) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{2} }

func (m *Law) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *Law) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Law) GetUpstream() string {
	if m != nil {
		return m.Upstream
	}
	return ""
}

func (m *Law) GetIdent() string {
	if m != nil {
		return m.Ident
	}
	return ""
}

func (m *Law) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Law) GetShortTitle() string {
	if m != nil {
		return m.ShortTitle
	}
	return ""
}

func (m *Law) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Law) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type Branch struct {
	Uid      string `protobuf:"bytes,1,opt,name=uid" json:"uid,omitempty"`
	LawId    string `protobuf:"bytes,2,opt,name=law_id,json=lawId" json:"law_id,omitempty"`
	UserId   string `protobuf:"bytes,3,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	Name     string `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	Upstream string `protobuf:"bytes,5,opt,name=upstream" json:"upstream,omitempty"`
}

func (m *Branch) Reset()                    { *m = Branch{} }
func (m *Branch) String() string            { return proto1.CompactTextString(m) }
func (*Branch) ProtoMessage()               {}
func (*Branch) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{3} }

func (m *Branch) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *Branch) GetLawId() string {
	if m != nil {
		return m.LawId
	}
	return ""
}

func (m *Branch) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Branch) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Branch) GetUpstream() string {
	if m != nil {
		return m.Upstream
	}
	return ""
}

type Version struct {
	Uid           string                     `protobuf:"bytes,1,opt,name=uid" json:"uid,omitempty"`
	BranchId      string                     `protobuf:"bytes,2,opt,name=branch_id,json=branchId" json:"branch_id,omitempty"`
	UserId        string                     `protobuf:"bytes,3,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	Version       uint32                     `protobuf:"varint,4,opt,name=version" json:"version,omitempty"`
	Hash          string                     `protobuf:"bytes,5,opt,name=hash" json:"hash,omitempty"`
	Description   string                     `protobuf:"bytes,6,opt,name=description" json:"description,omitempty"`
	Msg           string                     `protobuf:"bytes,7,opt,name=msg" json:"msg,omitempty"`
	Body          string                     `protobuf:"bytes,8,opt,name=body" json:"body,omitempty"`
	Label         string                     `protobuf:"bytes,9,opt,name=label" json:"label,omitempty"`
	PublishedAt   *google_protobuf.Timestamp `protobuf:"bytes,11,opt,name=published_at,json=publishedAt" json:"published_at,omitempty"`
	Tags          map[string]string          `protobuf:"bytes,12,rep,name=tags" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Yays          int32                      `protobuf:"varint,13,opt,name=yays" json:"yays,omitempty"`
	Nays          int32                      `protobuf:"varint,14,opt,name=nays" json:"nays,omitempty"`
	HasVoted      bool                       `protobuf:"varint,15,opt,name=has_voted,json=hasVoted" json:"has_voted,omitempty"`
	UpstreamGroup string                     `protobuf:"bytes,16,opt,name=upstream_group,json=upstreamGroup" json:"upstream_group,omitempty"`
	CommentCount  int32                      `protobuf:"varint,17,opt,name=comment_count,json=commentCount" json:"comment_count,omitempty"`
}

func (m *Version) Reset()                    { *m = Version{} }
func (m *Version) String() string            { return proto1.CompactTextString(m) }
func (*Version) ProtoMessage()               {}
func (*Version) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{4} }

func (m *Version) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *Version) GetBranchId() string {
	if m != nil {
		return m.BranchId
	}
	return ""
}

func (m *Version) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Version) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Version) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *Version) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Version) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *Version) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *Version) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *Version) GetPublishedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.PublishedAt
	}
	return nil
}

func (m *Version) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Version) GetYays() int32 {
	if m != nil {
		return m.Yays
	}
	return 0
}

func (m *Version) GetNays() int32 {
	if m != nil {
		return m.Nays
	}
	return 0
}

func (m *Version) GetHasVoted() bool {
	if m != nil {
		return m.HasVoted
	}
	return false
}

func (m *Version) GetUpstreamGroup() string {
	if m != nil {
		return m.UpstreamGroup
	}
	return ""
}

func (m *Version) GetCommentCount() int32 {
	if m != nil {
		return m.CommentCount
	}
	return 0
}

type CreateLawOptions struct {
	Branch  string `protobuf:"bytes,1,opt,name=branch" json:"branch,omitempty"`
	Version uint32 `protobuf:"varint,2,opt,name=version" json:"version,omitempty"`
}

func (m *CreateLawOptions) Reset()                    { *m = CreateLawOptions{} }
func (m *CreateLawOptions) String() string            { return proto1.CompactTextString(m) }
func (*CreateLawOptions) ProtoMessage()               {}
func (*CreateLawOptions) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{5} }

func (m *CreateLawOptions) GetBranch() string {
	if m != nil {
		return m.Branch
	}
	return ""
}

func (m *CreateLawOptions) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

type CreateLawsOptions struct {
	Branch  string `protobuf:"bytes,1,opt,name=branch" json:"branch,omitempty"`
	Version uint32 `protobuf:"varint,2,opt,name=version" json:"version,omitempty"`
}

func (m *CreateLawsOptions) Reset()                    { *m = CreateLawsOptions{} }
func (m *CreateLawsOptions) String() string            { return proto1.CompactTextString(m) }
func (*CreateLawsOptions) ProtoMessage()               {}
func (*CreateLawsOptions) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{6} }

func (m *CreateLawsOptions) GetBranch() string {
	if m != nil {
		return m.Branch
	}
	return ""
}

func (m *CreateLawsOptions) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

type CreateLawRequest struct {
	LawSet *LawSet           `protobuf:"bytes,1,opt,name=law_set,json=lawSet" json:"law_set,omitempty"`
	Opts   *CreateLawOptions `protobuf:"bytes,2,opt,name=opts" json:"opts,omitempty"`
}

func (m *CreateLawRequest) Reset()                    { *m = CreateLawRequest{} }
func (m *CreateLawRequest) String() string            { return proto1.CompactTextString(m) }
func (*CreateLawRequest) ProtoMessage()               {}
func (*CreateLawRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{7} }

func (m *CreateLawRequest) GetLawSet() *LawSet {
	if m != nil {
		return m.LawSet
	}
	return nil
}

func (m *CreateLawRequest) GetOpts() *CreateLawOptions {
	if m != nil {
		return m.Opts
	}
	return nil
}

type CreateLawReply struct {
	LawSet *LawSet `protobuf:"bytes,1,opt,name=law_set,json=lawSet" json:"law_set,omitempty"`
	Err    string  `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
}

func (m *CreateLawReply) Reset()                    { *m = CreateLawReply{} }
func (m *CreateLawReply) String() string            { return proto1.CompactTextString(m) }
func (*CreateLawReply) ProtoMessage()               {}
func (*CreateLawReply) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{8} }

func (m *CreateLawReply) GetLawSet() *LawSet {
	if m != nil {
		return m.LawSet
	}
	return nil
}

func (m *CreateLawReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type DeleteLawOptions struct {
	Branch  string `protobuf:"bytes,1,opt,name=branch" json:"branch,omitempty"`
	Version string `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
}

func (m *DeleteLawOptions) Reset()                    { *m = DeleteLawOptions{} }
func (m *DeleteLawOptions) String() string            { return proto1.CompactTextString(m) }
func (*DeleteLawOptions) ProtoMessage()               {}
func (*DeleteLawOptions) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{9} }

func (m *DeleteLawOptions) GetBranch() string {
	if m != nil {
		return m.Branch
	}
	return ""
}

func (m *DeleteLawOptions) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type DeleteLawRequest struct {
	Upstream string            `protobuf:"bytes,1,opt,name=upstream" json:"upstream,omitempty"`
	Ident    string            `protobuf:"bytes,2,opt,name=ident" json:"ident,omitempty"`
	Opts     *DeleteLawOptions `protobuf:"bytes,3,opt,name=opts" json:"opts,omitempty"`
}

func (m *DeleteLawRequest) Reset()                    { *m = DeleteLawRequest{} }
func (m *DeleteLawRequest) String() string            { return proto1.CompactTextString(m) }
func (*DeleteLawRequest) ProtoMessage()               {}
func (*DeleteLawRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{10} }

func (m *DeleteLawRequest) GetUpstream() string {
	if m != nil {
		return m.Upstream
	}
	return ""
}

func (m *DeleteLawRequest) GetIdent() string {
	if m != nil {
		return m.Ident
	}
	return ""
}

func (m *DeleteLawRequest) GetOpts() *DeleteLawOptions {
	if m != nil {
		return m.Opts
	}
	return nil
}

type DeleteLawReply struct {
	Err string `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
}

func (m *DeleteLawReply) Reset()                    { *m = DeleteLawReply{} }
func (m *DeleteLawReply) String() string            { return proto1.CompactTextString(m) }
func (*DeleteLawReply) ProtoMessage()               {}
func (*DeleteLawReply) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{11} }

func (m *DeleteLawReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type DiffLawsOptions struct {
	OurBranch    string `protobuf:"bytes,1,opt,name=our_branch,json=ourBranch" json:"our_branch,omitempty"`
	OurVersion   string `protobuf:"bytes,2,opt,name=our_version,json=ourVersion" json:"our_version,omitempty"`
	TheirBranch  string `protobuf:"bytes,3,opt,name=their_branch,json=theirBranch" json:"their_branch,omitempty"`
	TheirVersion string `protobuf:"bytes,4,opt,name=their_version,json=theirVersion" json:"their_version,omitempty"`
}

func (m *DiffLawsOptions) Reset()                    { *m = DiffLawsOptions{} }
func (m *DiffLawsOptions) String() string            { return proto1.CompactTextString(m) }
func (*DiffLawsOptions) ProtoMessage()               {}
func (*DiffLawsOptions) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{12} }

func (m *DiffLawsOptions) GetOurBranch() string {
	if m != nil {
		return m.OurBranch
	}
	return ""
}

func (m *DiffLawsOptions) GetOurVersion() string {
	if m != nil {
		return m.OurVersion
	}
	return ""
}

func (m *DiffLawsOptions) GetTheirBranch() string {
	if m != nil {
		return m.TheirBranch
	}
	return ""
}

func (m *DiffLawsOptions) GetTheirVersion() string {
	if m != nil {
		return m.TheirVersion
	}
	return ""
}

type DiffLawsRequest struct {
	Upstream string           `protobuf:"bytes,1,opt,name=upstream" json:"upstream,omitempty"`
	Ident    string           `protobuf:"bytes,2,opt,name=ident" json:"ident,omitempty"`
	Opts     *DiffLawsOptions `protobuf:"bytes,3,opt,name=opts" json:"opts,omitempty"`
}

func (m *DiffLawsRequest) Reset()                    { *m = DiffLawsRequest{} }
func (m *DiffLawsRequest) String() string            { return proto1.CompactTextString(m) }
func (*DiffLawsRequest) ProtoMessage()               {}
func (*DiffLawsRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{13} }

func (m *DiffLawsRequest) GetUpstream() string {
	if m != nil {
		return m.Upstream
	}
	return ""
}

func (m *DiffLawsRequest) GetIdent() string {
	if m != nil {
		return m.Ident
	}
	return ""
}

func (m *DiffLawsRequest) GetOpts() *DiffLawsOptions {
	if m != nil {
		return m.Opts
	}
	return nil
}

type DiffLawsReply struct {
	Diff   string  `protobuf:"bytes,1,opt,name=diff" json:"diff,omitempty"`
	Theirs *LawSet `protobuf:"bytes,2,opt,name=theirs" json:"theirs,omitempty"`
	Err    string  `protobuf:"bytes,3,opt,name=err" json:"err,omitempty"`
}

func (m *DiffLawsReply) Reset()                    { *m = DiffLawsReply{} }
func (m *DiffLawsReply) String() string            { return proto1.CompactTextString(m) }
func (*DiffLawsReply) ProtoMessage()               {}
func (*DiffLawsReply) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{14} }

func (m *DiffLawsReply) GetDiff() string {
	if m != nil {
		return m.Diff
	}
	return ""
}

func (m *DiffLawsReply) GetTheirs() *LawSet {
	if m != nil {
		return m.Theirs
	}
	return nil
}

func (m *DiffLawsReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type GetLawOptions struct {
	Branch  string `protobuf:"bytes,1,opt,name=branch" json:"branch,omitempty"`
	Version string `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
	Profile bool   `protobuf:"varint,3,opt,name=profile" json:"profile,omitempty"`
}

func (m *GetLawOptions) Reset()                    { *m = GetLawOptions{} }
func (m *GetLawOptions) String() string            { return proto1.CompactTextString(m) }
func (*GetLawOptions) ProtoMessage()               {}
func (*GetLawOptions) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{15} }

func (m *GetLawOptions) GetBranch() string {
	if m != nil {
		return m.Branch
	}
	return ""
}

func (m *GetLawOptions) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *GetLawOptions) GetProfile() bool {
	if m != nil {
		return m.Profile
	}
	return false
}

type GetLawRequest struct {
	Upstream string         `protobuf:"bytes,1,opt,name=upstream" json:"upstream,omitempty"`
	Ident    string         `protobuf:"bytes,2,opt,name=ident" json:"ident,omitempty"`
	Opts     *GetLawOptions `protobuf:"bytes,3,opt,name=opts" json:"opts,omitempty"`
}

func (m *GetLawRequest) Reset()                    { *m = GetLawRequest{} }
func (m *GetLawRequest) String() string            { return proto1.CompactTextString(m) }
func (*GetLawRequest) ProtoMessage()               {}
func (*GetLawRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{16} }

func (m *GetLawRequest) GetUpstream() string {
	if m != nil {
		return m.Upstream
	}
	return ""
}

func (m *GetLawRequest) GetIdent() string {
	if m != nil {
		return m.Ident
	}
	return ""
}

func (m *GetLawRequest) GetOpts() *GetLawOptions {
	if m != nil {
		return m.Opts
	}
	return nil
}

type GetLawReply struct {
	LawSet   *LawSet  `protobuf:"bytes,1,opt,name=law_set,json=lawSet" json:"law_set,omitempty"`
	Branches []string `protobuf:"bytes,2,rep,name=branches" json:"branches,omitempty"`
	Err      string   `protobuf:"bytes,3,opt,name=err" json:"err,omitempty"`
}

func (m *GetLawReply) Reset()                    { *m = GetLawReply{} }
func (m *GetLawReply) String() string            { return proto1.CompactTextString(m) }
func (*GetLawReply) ProtoMessage()               {}
func (*GetLawReply) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{17} }

func (m *GetLawReply) GetLawSet() *LawSet {
	if m != nil {
		return m.LawSet
	}
	return nil
}

func (m *GetLawReply) GetBranches() []string {
	if m != nil {
		return m.Branches
	}
	return nil
}

func (m *GetLawReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type ListLawsOptions struct {
	Upstream string `protobuf:"bytes,1,opt,name=upstream" json:"upstream,omitempty"`
	Ident    string `protobuf:"bytes,2,opt,name=ident" json:"ident,omitempty"`
	Branch   string `protobuf:"bytes,3,opt,name=branch" json:"branch,omitempty"`
	Username string `protobuf:"bytes,4,opt,name=username" json:"username,omitempty"`
	FromDate string `protobuf:"bytes,5,opt,name=from_date,json=fromDate" json:"from_date,omitempty"`
	ToDate   string `protobuf:"bytes,6,opt,name=to_date,json=toDate" json:"to_date,omitempty"`
	// int32 limit = 7;
	PageSize int32                       `protobuf:"varint,8,opt,name=page_size,json=pageSize" json:"page_size,omitempty"`
	PageNum  int32                       `protobuf:"varint,9,opt,name=page_num,json=pageNum" json:"page_num,omitempty"`
	Desc     bool                        `protobuf:"varint,11,opt,name=desc" json:"desc,omitempty"`
	OrderBy  string                      `protobuf:"bytes,12,opt,name=order_by,json=orderBy" json:"order_by,omitempty"`
	Search   string                      `protobuf:"bytes,13,opt,name=search" json:"search,omitempty"`
	ReqType  ListLawsOptions_RequestType `protobuf:"varint,14,opt,name=req_type,json=reqType,enum=proto.ListLawsOptions_RequestType" json:"req_type,omitempty"`
}

func (m *ListLawsOptions) Reset()                    { *m = ListLawsOptions{} }
func (m *ListLawsOptions) String() string            { return proto1.CompactTextString(m) }
func (*ListLawsOptions) ProtoMessage()               {}
func (*ListLawsOptions) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{18} }

func (m *ListLawsOptions) GetUpstream() string {
	if m != nil {
		return m.Upstream
	}
	return ""
}

func (m *ListLawsOptions) GetIdent() string {
	if m != nil {
		return m.Ident
	}
	return ""
}

func (m *ListLawsOptions) GetBranch() string {
	if m != nil {
		return m.Branch
	}
	return ""
}

func (m *ListLawsOptions) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ListLawsOptions) GetFromDate() string {
	if m != nil {
		return m.FromDate
	}
	return ""
}

func (m *ListLawsOptions) GetToDate() string {
	if m != nil {
		return m.ToDate
	}
	return ""
}

func (m *ListLawsOptions) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListLawsOptions) GetPageNum() int32 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

func (m *ListLawsOptions) GetDesc() bool {
	if m != nil {
		return m.Desc
	}
	return false
}

func (m *ListLawsOptions) GetOrderBy() string {
	if m != nil {
		return m.OrderBy
	}
	return ""
}

func (m *ListLawsOptions) GetSearch() string {
	if m != nil {
		return m.Search
	}
	return ""
}

func (m *ListLawsOptions) GetReqType() ListLawsOptions_RequestType {
	if m != nil {
		return m.ReqType
	}
	return ListLawsOptions_USER_LAWS
}

type ListLawsRequest struct {
	Opts *ListLawsOptions `protobuf:"bytes,1,opt,name=opts" json:"opts,omitempty"`
}

func (m *ListLawsRequest) Reset()                    { *m = ListLawsRequest{} }
func (m *ListLawsRequest) String() string            { return proto1.CompactTextString(m) }
func (*ListLawsRequest) ProtoMessage()               {}
func (*ListLawsRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{19} }

func (m *ListLawsRequest) GetOpts() *ListLawsOptions {
	if m != nil {
		return m.Opts
	}
	return nil
}

type ListLawsReply struct {
	LawSets     []*LawSet `protobuf:"bytes,1,rep,name=law_sets,json=lawSets" json:"law_sets,omitempty"`
	Total       int32     `protobuf:"varint,2,opt,name=total" json:"total,omitempty"`
	Suggestions []string  `protobuf:"bytes,3,rep,name=suggestions" json:"suggestions,omitempty"`
	Err         string    `protobuf:"bytes,4,opt,name=err" json:"err,omitempty"`
}

func (m *ListLawsReply) Reset()                    { *m = ListLawsReply{} }
func (m *ListLawsReply) String() string            { return proto1.CompactTextString(m) }
func (*ListLawsReply) ProtoMessage()               {}
func (*ListLawsReply) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{20} }

func (m *ListLawsReply) GetLawSets() []*LawSet {
	if m != nil {
		return m.LawSets
	}
	return nil
}

func (m *ListLawsReply) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ListLawsReply) GetSuggestions() []string {
	if m != nil {
		return m.Suggestions
	}
	return nil
}

func (m *ListLawsReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type UpdateLawOptions struct {
	Branch  string `protobuf:"bytes,1,opt,name=branch" json:"branch,omitempty"`
	Version string `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
}

func (m *UpdateLawOptions) Reset()                    { *m = UpdateLawOptions{} }
func (m *UpdateLawOptions) String() string            { return proto1.CompactTextString(m) }
func (*UpdateLawOptions) ProtoMessage()               {}
func (*UpdateLawOptions) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{21} }

func (m *UpdateLawOptions) GetBranch() string {
	if m != nil {
		return m.Branch
	}
	return ""
}

func (m *UpdateLawOptions) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type UpdateLawRequest struct {
	Law  *Law              `protobuf:"bytes,1,opt,name=law" json:"law,omitempty"`
	Opts *UpdateLawOptions `protobuf:"bytes,2,opt,name=opts" json:"opts,omitempty"`
}

func (m *UpdateLawRequest) Reset()                    { *m = UpdateLawRequest{} }
func (m *UpdateLawRequest) String() string            { return proto1.CompactTextString(m) }
func (*UpdateLawRequest) ProtoMessage()               {}
func (*UpdateLawRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{22} }

func (m *UpdateLawRequest) GetLaw() *Law {
	if m != nil {
		return m.Law
	}
	return nil
}

func (m *UpdateLawRequest) GetOpts() *UpdateLawOptions {
	if m != nil {
		return m.Opts
	}
	return nil
}

type UpdateLawReply struct {
	Err string `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
}

func (m *UpdateLawReply) Reset()                    { *m = UpdateLawReply{} }
func (m *UpdateLawReply) String() string            { return proto1.CompactTextString(m) }
func (*UpdateLawReply) ProtoMessage()               {}
func (*UpdateLawReply) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{23} }

func (m *UpdateLawReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func init() {
	proto1.RegisterType((*LawSet)(nil), "proto.LawSet")
	proto1.RegisterType((*Author)(nil), "proto.Author")
	proto1.RegisterType((*Law)(nil), "proto.Law")
	proto1.RegisterType((*Branch)(nil), "proto.Branch")
	proto1.RegisterType((*Version)(nil), "proto.Version")
	proto1.RegisterType((*CreateLawOptions)(nil), "proto.CreateLawOptions")
	proto1.RegisterType((*CreateLawsOptions)(nil), "proto.CreateLawsOptions")
	proto1.RegisterType((*CreateLawRequest)(nil), "proto.CreateLawRequest")
	proto1.RegisterType((*CreateLawReply)(nil), "proto.CreateLawReply")
	proto1.RegisterType((*DeleteLawOptions)(nil), "proto.DeleteLawOptions")
	proto1.RegisterType((*DeleteLawRequest)(nil), "proto.DeleteLawRequest")
	proto1.RegisterType((*DeleteLawReply)(nil), "proto.DeleteLawReply")
	proto1.RegisterType((*DiffLawsOptions)(nil), "proto.DiffLawsOptions")
	proto1.RegisterType((*DiffLawsRequest)(nil), "proto.DiffLawsRequest")
	proto1.RegisterType((*DiffLawsReply)(nil), "proto.DiffLawsReply")
	proto1.RegisterType((*GetLawOptions)(nil), "proto.GetLawOptions")
	proto1.RegisterType((*GetLawRequest)(nil), "proto.GetLawRequest")
	proto1.RegisterType((*GetLawReply)(nil), "proto.GetLawReply")
	proto1.RegisterType((*ListLawsOptions)(nil), "proto.ListLawsOptions")
	proto1.RegisterType((*ListLawsRequest)(nil), "proto.ListLawsRequest")
	proto1.RegisterType((*ListLawsReply)(nil), "proto.ListLawsReply")
	proto1.RegisterType((*UpdateLawOptions)(nil), "proto.UpdateLawOptions")
	proto1.RegisterType((*UpdateLawRequest)(nil), "proto.UpdateLawRequest")
	proto1.RegisterType((*UpdateLawReply)(nil), "proto.UpdateLawReply")
	proto1.RegisterEnum("proto.ListLawsOptions_RequestType", ListLawsOptions_RequestType_name, ListLawsOptions_RequestType_value)
}

func init() { proto1.RegisterFile("proto/law.proto", fileDescriptor4) }

var fileDescriptor4 = []byte{
	// 1286 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x57, 0x5f, 0x6f, 0x1b, 0x45,
	0x10, 0xe7, 0x72, 0xfe, 0x77, 0xe3, 0x38, 0x71, 0x97, 0xd2, 0x1e, 0x29, 0x28, 0xe1, 0xaa, 0x22,
	0x0b, 0x90, 0x2b, 0x95, 0x07, 0x10, 0x52, 0x1f, 0xdc, 0xc4, 0x6a, 0x8b, 0x4c, 0x8a, 0xd6, 0x49,
	0xfb, 0x00, 0xe8, 0xb4, 0xb6, 0xd7, 0xf6, 0xa9, 0x67, 0xdf, 0x65, 0x77, 0xaf, 0x96, 0xf3, 0xca,
	0x1b, 0xcf, 0xbc, 0xf0, 0x69, 0xf8, 0x04, 0x88, 0xaf, 0x84, 0xf6, 0x9f, 0xef, 0xce, 0x98, 0x8a,
	0xa6, 0x4f, 0x9e, 0x99, 0x9d, 0x9d, 0xfd, 0xcd, 0x6f, 0x67, 0x67, 0xce, 0x70, 0x98, 0xb2, 0x44,
	0x24, 0x0f, 0x63, 0xb2, 0xea, 0x2a, 0x09, 0x55, 0xd5, 0xcf, 0xd1, 0xf1, 0x2c, 0x49, 0x66, 0x31,
	0x7d, 0xa8, 0xb4, 0x51, 0x36, 0x7d, 0x28, 0xa2, 0x05, 0xe5, 0x82, 0x2c, 0x52, 0xed, 0x77, 0xd4,
	0xd6, 0x1b, 0x33, 0x4e, 0x99, 0xb6, 0x04, 0x7f, 0x3a, 0x50, 0x1b, 0x90, 0xd5, 0x90, 0x0a, 0xf4,
	0x09, 0xb8, 0x31, 0x59, 0xf9, 0xce, 0x89, 0xd3, 0x69, 0x3e, 0x02, 0xbd, 0xde, 0x1d, 0x90, 0x15,
	0x96, 0x66, 0xf4, 0x00, 0x6a, 0x23, 0x46, 0x96, 0xe3, 0xb9, 0xbf, 0xa7, 0x1c, 0x5a, 0xc6, 0xe1,
	0x89, 0x32, 0x62, 0xb3, 0x88, 0x3a, 0x50, 0x7f, 0x43, 0x19, 0x8f, 0x92, 0xa5, 0xef, 0x2a, 0xbf,
	0x03, 0xe3, 0xf7, 0x52, 0x5b, 0xb1, 0x5d, 0x96, 0x01, 0x49, 0x26, 0xe6, 0x09, 0xf3, 0x2b, 0xa5,
	0x80, 0x3d, 0x65, 0xc4, 0x66, 0x11, 0x1d, 0x43, 0x45, 0xc2, 0xf5, 0xab, 0xca, 0xa9, 0x69, 0x9c,
	0x2e, 0x39, 0x65, 0x58, 0x2d, 0x04, 0xbf, 0x39, 0x50, 0xd3, 0x7b, 0x50, 0x1b, 0xdc, 0x2c, 0x9a,
	0xa8, 0x0c, 0x3c, 0x2c, 0x45, 0x74, 0x04, 0x0d, 0xe9, 0xb4, 0x24, 0x0b, 0xaa, 0x70, 0x7b, 0x78,
	0xa3, 0xa3, 0xdb, 0x50, 0xa5, 0x0b, 0x12, 0xc5, 0x0a, 0xa8, 0x87, 0xb5, 0x82, 0xee, 0x81, 0x37,
	0xcd, 0xe2, 0x38, 0x54, 0x5b, 0x2a, 0x7a, 0x8b, 0x34, 0x9c, 0xcb, 0x2d, 0xc7, 0xd0, 0x4c, 0xa3,
	0xb1, 0xc8, 0x18, 0x0d, 0x33, 0x16, 0x2b, 0x4c, 0x1e, 0x06, 0x63, 0xba, 0x64, 0x71, 0xf0, 0x97,
	0x03, 0xee, 0x80, 0xac, 0x76, 0x20, 0xb9, 0x0b, 0x75, 0x79, 0x72, 0x18, 0x4d, 0x0c, 0x90, 0x9a,
	0x54, 0x9f, 0x6b, 0x88, 0x29, 0x17, 0x8c, 0x92, 0x85, 0x41, 0xb2, 0xd1, 0x25, 0xc4, 0x68, 0x42,
	0x97, 0xc2, 0x00, 0xd1, 0x8a, 0xb4, 0x8a, 0x48, 0xc4, 0xd4, 0x9c, 0xaf, 0x15, 0x89, 0x8d, 0xcf,
	0x13, 0x26, 0x42, 0xbd, 0x56, 0xd3, 0xd8, 0x94, 0xe9, 0x42, 0x39, 0x9c, 0x40, 0x73, 0x42, 0xf9,
	0x98, 0x45, 0xa9, 0x90, 0xd7, 0x53, 0x57, 0x0e, 0x45, 0x93, 0x42, 0xcd, 0x62, 0xbf, 0x61, 0x50,
	0xb3, 0x38, 0xb8, 0x86, 0x9a, 0xbe, 0xe0, 0x1d, 0x19, 0x7d, 0x04, 0xb5, 0x98, 0xac, 0xf2, 0x84,
	0xaa, 0x31, 0x59, 0x3d, 0x2f, 0x25, 0xea, 0x96, 0x12, 0x45, 0x50, 0x29, 0x90, 0xaa, 0xe4, 0x52,
	0xf2, 0xd5, 0x72, 0xf2, 0xc1, 0xef, 0x15, 0xa8, 0x9b, 0xaa, 0xd9, 0x71, 0xfa, 0x3d, 0xf0, 0x74,
	0xc9, 0xe5, 0x00, 0x1a, 0xda, 0xf0, 0x36, 0x0c, 0x7e, 0x5e, 0x9e, 0x12, 0x46, 0x2b, 0x2f, 0x47,
	0x04, 0x95, 0x39, 0xe1, 0x73, 0x83, 0x42, 0xc9, 0xdb, 0x8c, 0xd5, 0x76, 0x32, 0xb6, 0xe0, 0x33,
	0xc3, 0xa5, 0x14, 0x65, 0x9c, 0x51, 0x32, 0x59, 0x1b, 0x12, 0x95, 0x2c, 0x2f, 0x2c, 0x26, 0x23,
	0x1a, 0xfb, 0x9e, 0x25, 0x6a, 0x44, 0x63, 0xf4, 0x18, 0xf6, 0xd3, 0x6c, 0x14, 0x47, 0x7c, 0x4e,
	0x27, 0x21, 0x11, 0x7e, 0x53, 0x55, 0xf8, 0x51, 0x57, 0x3f, 0xe2, 0xae, 0x7d, 0xc4, 0xdd, 0x0b,
	0xfb, 0x88, 0x71, 0x73, 0xe3, 0xdf, 0x13, 0xe8, 0x2b, 0xa8, 0x08, 0x32, 0xe3, 0xfe, 0xfe, 0x89,
	0xdb, 0x69, 0x3e, 0xf2, 0xcb, 0xcf, 0xac, 0x7b, 0x41, 0x66, 0xbc, 0xbf, 0x14, 0x6c, 0x8d, 0x95,
	0x97, 0x84, 0xb5, 0x26, 0x6b, 0xee, 0xb7, 0x4e, 0x9c, 0x4e, 0x15, 0x2b, 0x59, 0x5f, 0xc8, 0x9a,
	0xfb, 0x07, 0xda, 0x26, 0x65, 0x49, 0xeb, 0x9c, 0xf0, 0xf0, 0x4d, 0x22, 0xe8, 0xc4, 0x3f, 0x3c,
	0x71, 0x3a, 0x0d, 0xdc, 0x98, 0x13, 0xfe, 0x52, 0xea, 0xe8, 0x01, 0x1c, 0xd8, 0xdb, 0x09, 0x67,
	0x2c, 0xc9, 0x52, 0xbf, 0xad, 0x12, 0x6a, 0x59, 0xeb, 0x53, 0x69, 0x44, 0xf7, 0xa1, 0x35, 0x4e,
	0x16, 0x0b, 0xba, 0x14, 0xe1, 0x38, 0xc9, 0x96, 0xc2, 0xbf, 0xa5, 0x0e, 0xd8, 0x37, 0xc6, 0x53,
	0x69, 0x3b, 0xfa, 0x06, 0xbc, 0x0d, 0x46, 0x49, 0xe3, 0x6b, 0xba, 0xb6, 0xd7, 0xfb, 0x9a, 0x2a,
	0xca, 0xde, 0x90, 0x38, 0xb3, 0xaf, 0x56, 0x2b, 0xdf, 0xed, 0x7d, 0xeb, 0x04, 0x67, 0xd0, 0x3e,
	0x65, 0x94, 0x08, 0x3a, 0x20, 0xab, 0x17, 0xea, 0x16, 0x38, 0xba, 0xb3, 0x69, 0x4e, 0x3a, 0x84,
	0xed, 0x46, 0x85, 0xeb, 0xde, 0x2b, 0x5d, 0x77, 0xd0, 0x87, 0x5b, 0x9b, 0x28, 0xfc, 0xe6, 0x61,
	0x66, 0x05, 0x30, 0x98, 0x5e, 0x65, 0x94, 0x0b, 0xf4, 0x39, 0xd4, 0xe5, 0xbb, 0xe0, 0x54, 0x98,
	0x5e, 0xda, 0xca, 0x7b, 0xe9, 0x90, 0x0a, 0x2c, 0x5f, 0x8d, 0xec, 0xb7, 0x5f, 0x42, 0x25, 0x49,
	0x05, 0x37, 0xfd, 0xf4, 0xae, 0x71, 0xda, 0xce, 0x0d, 0x2b, 0xa7, 0xe0, 0x7b, 0x38, 0x28, 0x1c,
	0x94, 0xc6, 0xeb, 0xff, 0x7d, 0x4c, 0x1b, 0x5c, 0xca, 0x98, 0xe1, 0x51, 0x8a, 0x92, 0xc1, 0x33,
	0x1a, 0xd3, 0x9b, 0x30, 0xe8, 0xe5, 0xa9, 0x5f, 0x15, 0xa2, 0xd8, 0xd4, 0x8b, 0xcf, 0xd9, 0xf9,
	0xaf, 0x5e, 0xb6, 0x57, 0xec, 0x65, 0x96, 0x04, 0xb7, 0x44, 0xc2, 0x36, 0x3c, 0x43, 0x42, 0x00,
	0x07, 0x85, 0x23, 0x25, 0x09, 0x26, 0x39, 0x27, 0x4f, 0xee, 0x0f, 0x07, 0x0e, 0xcf, 0xa2, 0xe9,
	0xb4, 0x78, 0xaf, 0x9f, 0x02, 0x24, 0x19, 0x0b, 0x4b, 0x09, 0x7a, 0x49, 0xc6, 0x4c, 0x6b, 0x3b,
	0x86, 0xa6, 0x5c, 0x2e, 0xe7, 0x29, 0x77, 0xd8, 0xee, 0xf3, 0x19, 0xec, 0x8b, 0x39, 0x8d, 0x36,
	0x11, 0x74, 0x4f, 0x69, 0x2a, 0x9b, 0x89, 0x71, 0x1f, 0x5a, 0xda, 0xa5, 0xd8, 0x5e, 0x3c, 0xac,
	0xf7, 0x99, 0x38, 0x41, 0x92, 0x43, 0xbb, 0x39, 0x63, 0x5f, 0x94, 0x18, 0xbb, 0x63, 0x19, 0x2b,
	0xa7, 0x6c, 0x08, 0xfb, 0x19, 0x5a, 0xf9, 0x81, 0x92, 0x2f, 0x04, 0x95, 0x49, 0x34, 0x9d, 0x9a,
	0xa3, 0x94, 0x2c, 0x07, 0xb1, 0x42, 0xc9, 0xb7, 0x26, 0xbb, 0xad, 0x23, 0xbd, 0x68, 0xa9, 0x76,
	0x73, 0xaa, 0x7f, 0x82, 0xd6, 0x53, 0x2a, 0xde, 0xa7, 0x88, 0xe4, 0x4a, 0xca, 0x92, 0x69, 0x14,
	0x53, 0x15, 0xb8, 0x81, 0xad, 0x1a, 0xbc, 0xb6, 0xc1, 0x6f, 0xce, 0x54, 0xa7, 0xc4, 0xd4, 0x6d,
	0x93, 0x56, 0x09, 0xb2, 0xe1, 0x69, 0x0c, 0x4d, 0x7b, 0xd8, 0xbb, 0x3c, 0xad, 0x23, 0x30, 0x23,
	0x87, 0x4a, 0xee, 0xdc, 0x7c, 0x04, 0xd1, 0x5d, 0x74, 0xfd, 0xed, 0xc2, 0xe1, 0x20, 0xe2, 0xa2,
	0x58, 0x99, 0xef, 0x9e, 0x54, 0xce, 0xb1, 0x5b, 0xe2, 0xb8, 0xf8, 0xa5, 0x53, 0xd9, 0xfa, 0xd2,
	0x91, 0xdf, 0x34, 0x2c, 0x59, 0x84, 0x13, 0x22, 0xec, 0x47, 0x43, 0x43, 0x1a, 0xce, 0x88, 0xa0,
	0x72, 0x56, 0x8a, 0x44, 0x2f, 0xe9, 0x01, 0x57, 0x13, 0x89, 0x5a, 0xb8, 0x07, 0x5e, 0x4a, 0x66,
	0x34, 0xe4, 0xd1, 0x35, 0x55, 0xe3, 0xac, 0x8a, 0x1b, 0xd2, 0x30, 0x8c, 0xae, 0x29, 0xfa, 0x18,
	0x94, 0x1c, 0x2e, 0xb3, 0x85, 0x9a, 0x6a, 0x55, 0x5c, 0x97, 0xfa, 0x79, 0xb6, 0x50, 0x35, 0x46,
	0xf9, 0x58, 0xcd, 0xb3, 0x06, 0x56, 0xb2, 0x74, 0x4f, 0xd8, 0x84, 0xb2, 0x70, 0xb4, 0xf6, 0xf7,
	0x75, 0x09, 0x28, 0xfd, 0xc9, 0x5a, 0x26, 0xc4, 0x29, 0x61, 0xe3, 0xb9, 0x9a, 0x4d, 0x1e, 0x36,
	0x1a, 0x7a, 0x0c, 0x0d, 0x46, 0xaf, 0x42, 0xb1, 0x4e, 0xa9, 0x9a, 0x50, 0x07, 0x8f, 0x02, 0x7b,
	0x0b, 0x65, 0x12, 0xbb, 0xa6, 0x42, 0x2e, 0xd6, 0x29, 0xc5, 0x75, 0x46, 0xaf, 0xa4, 0x10, 0x8c,
	0xa0, 0x59, 0xb0, 0xa3, 0x16, 0x78, 0x97, 0xc3, 0x3e, 0x0e, 0x07, 0xbd, 0x57, 0xc3, 0xf6, 0x07,
	0xe8, 0x16, 0xb4, 0x2e, 0x7f, 0x1c, 0x5e, 0xe0, 0x7e, 0xef, 0x07, 0x6d, 0x72, 0x10, 0x40, 0x6d,
	0xd8, 0xef, 0xe1, 0xd3, 0x67, 0xed, 0x3d, 0xd4, 0x86, 0xfd, 0x41, 0xef, 0x55, 0xf8, 0x04, 0xf7,
	0xce, 0x4f, 0x9f, 0xf5, 0x87, 0x6d, 0x17, 0x7d, 0x08, 0x87, 0x5a, 0x0b, 0x5f, 0xf6, 0xf1, 0xf0,
	0xf9, 0x8b, 0xf3, 0x61, 0xbb, 0x12, 0x3c, 0xce, 0x2f, 0xd4, 0x56, 0xa9, 0x7d, 0x9d, 0x4e, 0xe9,
	0x75, 0x6e, 0x21, 0x36, 0x55, 0xf7, 0xab, 0x03, 0xad, 0x7c, 0xbf, 0x2c, 0xbc, 0x0e, 0x34, 0x4c,
	0xe1, 0xc9, 0x08, 0xee, 0xbf, 0x2b, 0xaf, 0xae, 0x2b, 0x8f, 0xab, 0x6f, 0xc0, 0x44, 0x90, 0x58,
	0x15, 0x47, 0x15, 0x6b, 0x45, 0x7e, 0xb0, 0xf0, 0x6c, 0x36, 0xa3, 0x5c, 0x1d, 0xe3, 0xbb, 0xaa,
	0x26, 0x8b, 0x26, 0x5b, 0x96, 0x95, 0xd2, 0x34, 0xb8, 0x4c, 0x27, 0xe4, 0x3d, 0xa7, 0xc1, 0x2f,
	0x85, 0x28, 0x96, 0x8b, 0xb7, 0xff, 0xa1, 0xd8, 0x3d, 0xfe, 0xb6, 0xa1, 0xe4, 0x9d, 0xbf, 0x10,
	0x7e, 0x67, 0xe7, 0x1f, 0xd5, 0x54, 0x84, 0xaf, 0xff, 0x09, 0x00, 0x00, 0xff, 0xff, 0xf9, 0x4a,
	0xca, 0x1d, 0x1e, 0x0d, 0x00, 0x00,
}
