// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/upstream.proto

package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Upstream struct {
	Ident               string            `protobuf:"bytes,1,opt,name=ident" json:"ident,omitempty"`
	UpstreamName        string            `protobuf:"bytes,2,opt,name=upstream_name,json=upstreamName" json:"upstream_name,omitempty"`
	UpstreamDescription string            `protobuf:"bytes,3,opt,name=upstream_description,json=upstreamDescription" json:"upstream_description,omitempty"`
	Name                string            `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	Description         string            `protobuf:"bytes,5,opt,name=description" json:"description,omitempty"`
	Url                 string            `protobuf:"bytes,6,opt,name=url" json:"url,omitempty"`
	Email               string            `protobuf:"bytes,7,opt,name=email" json:"email,omitempty"`
	DefaultUser         string            `protobuf:"bytes,8,opt,name=default_user,json=defaultUser" json:"default_user,omitempty"`
	GeoCoords           string            `protobuf:"bytes,9,opt,name=geo_coords,json=geoCoords" json:"geo_coords,omitempty"`
	Laws                int32             `protobuf:"varint,10,opt,name=laws" json:"laws,omitempty"`
	Users               int32             `protobuf:"varint,11,opt,name=users" json:"users,omitempty"`
	Metadata            *UpstreamMetadata `protobuf:"bytes,12,opt,name=metadata" json:"metadata,omitempty"`
	Uid                 string            `protobuf:"bytes,13,opt,name=uid" json:"uid,omitempty"`
	UserId              string            `protobuf:"bytes,14,opt,name=user_id,json=userId" json:"user_id,omitempty"`
}

func (m *Upstream) Reset()                    { *m = Upstream{} }
func (m *Upstream) String() string            { return proto1.CompactTextString(m) }
func (*Upstream) ProtoMessage()               {}
func (*Upstream) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{0} }

func (m *Upstream) GetIdent() string {
	if m != nil {
		return m.Ident
	}
	return ""
}

func (m *Upstream) GetUpstreamName() string {
	if m != nil {
		return m.UpstreamName
	}
	return ""
}

func (m *Upstream) GetUpstreamDescription() string {
	if m != nil {
		return m.UpstreamDescription
	}
	return ""
}

func (m *Upstream) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Upstream) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Upstream) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Upstream) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Upstream) GetDefaultUser() string {
	if m != nil {
		return m.DefaultUser
	}
	return ""
}

func (m *Upstream) GetGeoCoords() string {
	if m != nil {
		return m.GeoCoords
	}
	return ""
}

func (m *Upstream) GetLaws() int32 {
	if m != nil {
		return m.Laws
	}
	return 0
}

func (m *Upstream) GetUsers() int32 {
	if m != nil {
		return m.Users
	}
	return 0
}

func (m *Upstream) GetMetadata() *UpstreamMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Upstream) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *Upstream) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type UpstreamMetadata struct {
	Email     string `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	Wikipedia string `protobuf:"bytes,2,opt,name=wikipedia" json:"wikipedia,omitempty"`
	Twitter   string `protobuf:"bytes,3,opt,name=twitter" json:"twitter,omitempty"`
	ApiUrl    string `protobuf:"bytes,4,opt,name=api_url,json=apiUrl" json:"api_url,omitempty"`
	Facebook  string `protobuf:"bytes,5,opt,name=facebook" json:"facebook,omitempty"`
}

func (m *UpstreamMetadata) Reset()                    { *m = UpstreamMetadata{} }
func (m *UpstreamMetadata) String() string            { return proto1.CompactTextString(m) }
func (*UpstreamMetadata) ProtoMessage()               {}
func (*UpstreamMetadata) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{1} }

func (m *UpstreamMetadata) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UpstreamMetadata) GetWikipedia() string {
	if m != nil {
		return m.Wikipedia
	}
	return ""
}

func (m *UpstreamMetadata) GetTwitter() string {
	if m != nil {
		return m.Twitter
	}
	return ""
}

func (m *UpstreamMetadata) GetApiUrl() string {
	if m != nil {
		return m.ApiUrl
	}
	return ""
}

func (m *UpstreamMetadata) GetFacebook() string {
	if m != nil {
		return m.Facebook
	}
	return ""
}

type CreateUpstreamRequest struct {
	Upstream *Upstream `protobuf:"bytes,1,opt,name=upstream" json:"upstream,omitempty"`
}

func (m *CreateUpstreamRequest) Reset()                    { *m = CreateUpstreamRequest{} }
func (m *CreateUpstreamRequest) String() string            { return proto1.CompactTextString(m) }
func (*CreateUpstreamRequest) ProtoMessage()               {}
func (*CreateUpstreamRequest) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{2} }

func (m *CreateUpstreamRequest) GetUpstream() *Upstream {
	if m != nil {
		return m.Upstream
	}
	return nil
}

type CreateUpstreamReply struct {
	Err string `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
}

func (m *CreateUpstreamReply) Reset()                    { *m = CreateUpstreamReply{} }
func (m *CreateUpstreamReply) String() string            { return proto1.CompactTextString(m) }
func (*CreateUpstreamReply) ProtoMessage()               {}
func (*CreateUpstreamReply) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{3} }

func (m *CreateUpstreamReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type GetUpstreamRequest struct {
	Ident string `protobuf:"bytes,1,opt,name=ident" json:"ident,omitempty"`
}

func (m *GetUpstreamRequest) Reset()                    { *m = GetUpstreamRequest{} }
func (m *GetUpstreamRequest) String() string            { return proto1.CompactTextString(m) }
func (*GetUpstreamRequest) ProtoMessage()               {}
func (*GetUpstreamRequest) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{4} }

func (m *GetUpstreamRequest) GetIdent() string {
	if m != nil {
		return m.Ident
	}
	return ""
}

type GetUpstreamReply struct {
	Upstream *Upstream `protobuf:"bytes,1,opt,name=upstream" json:"upstream,omitempty"`
	Laws     []*LawSet `protobuf:"bytes,2,rep,name=laws" json:"laws,omitempty"`
	Users    []*User   `protobuf:"bytes,3,rep,name=users" json:"users,omitempty"`
	Err      string    `protobuf:"bytes,4,opt,name=err" json:"err,omitempty"`
}

func (m *GetUpstreamReply) Reset()                    { *m = GetUpstreamReply{} }
func (m *GetUpstreamReply) String() string            { return proto1.CompactTextString(m) }
func (*GetUpstreamReply) ProtoMessage()               {}
func (*GetUpstreamReply) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{5} }

func (m *GetUpstreamReply) GetUpstream() *Upstream {
	if m != nil {
		return m.Upstream
	}
	return nil
}

func (m *GetUpstreamReply) GetLaws() []*LawSet {
	if m != nil {
		return m.Laws
	}
	return nil
}

func (m *GetUpstreamReply) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *GetUpstreamReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type ListUpstreamsRequest struct {
}

func (m *ListUpstreamsRequest) Reset()                    { *m = ListUpstreamsRequest{} }
func (m *ListUpstreamsRequest) String() string            { return proto1.CompactTextString(m) }
func (*ListUpstreamsRequest) ProtoMessage()               {}
func (*ListUpstreamsRequest) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{6} }

type ListUpstreamsReply struct {
	Upstreams []*Upstream `protobuf:"bytes,1,rep,name=upstreams" json:"upstreams,omitempty"`
	Err       string      `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
}

func (m *ListUpstreamsReply) Reset()                    { *m = ListUpstreamsReply{} }
func (m *ListUpstreamsReply) String() string            { return proto1.CompactTextString(m) }
func (*ListUpstreamsReply) ProtoMessage()               {}
func (*ListUpstreamsReply) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{7} }

func (m *ListUpstreamsReply) GetUpstreams() []*Upstream {
	if m != nil {
		return m.Upstreams
	}
	return nil
}

func (m *ListUpstreamsReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type UpdateUpstreamRequest struct {
	Upstream *Upstream `protobuf:"bytes,1,opt,name=upstream" json:"upstream,omitempty"`
}

func (m *UpdateUpstreamRequest) Reset()                    { *m = UpdateUpstreamRequest{} }
func (m *UpdateUpstreamRequest) String() string            { return proto1.CompactTextString(m) }
func (*UpdateUpstreamRequest) ProtoMessage()               {}
func (*UpdateUpstreamRequest) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{8} }

func (m *UpdateUpstreamRequest) GetUpstream() *Upstream {
	if m != nil {
		return m.Upstream
	}
	return nil
}

type UpdateUpstreamReply struct {
	Err string `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
}

func (m *UpdateUpstreamReply) Reset()                    { *m = UpdateUpstreamReply{} }
func (m *UpdateUpstreamReply) String() string            { return proto1.CompactTextString(m) }
func (*UpdateUpstreamReply) ProtoMessage()               {}
func (*UpdateUpstreamReply) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{9} }

func (m *UpdateUpstreamReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func init() {
	proto1.RegisterType((*Upstream)(nil), "proto.Upstream")
	proto1.RegisterType((*UpstreamMetadata)(nil), "proto.UpstreamMetadata")
	proto1.RegisterType((*CreateUpstreamRequest)(nil), "proto.CreateUpstreamRequest")
	proto1.RegisterType((*CreateUpstreamReply)(nil), "proto.CreateUpstreamReply")
	proto1.RegisterType((*GetUpstreamRequest)(nil), "proto.GetUpstreamRequest")
	proto1.RegisterType((*GetUpstreamReply)(nil), "proto.GetUpstreamReply")
	proto1.RegisterType((*ListUpstreamsRequest)(nil), "proto.ListUpstreamsRequest")
	proto1.RegisterType((*ListUpstreamsReply)(nil), "proto.ListUpstreamsReply")
	proto1.RegisterType((*UpdateUpstreamRequest)(nil), "proto.UpdateUpstreamRequest")
	proto1.RegisterType((*UpdateUpstreamReply)(nil), "proto.UpdateUpstreamReply")
}

func init() { proto1.RegisterFile("proto/upstream.proto", fileDescriptor5) }

var fileDescriptor5 = []byte{
	// 520 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x52, 0x4d, 0x6f, 0x13, 0x31,
	0x10, 0xd5, 0xe6, 0x3b, 0xb3, 0x09, 0x8d, 0xdc, 0x94, 0x5a, 0x11, 0x48, 0xc9, 0x72, 0x20, 0x02,
	0x51, 0x44, 0xfa, 0x13, 0x1a, 0x09, 0x21, 0x15, 0x0e, 0x41, 0x39, 0x47, 0x6e, 0x3c, 0xad, 0xac,
	0x6e, 0xb2, 0x8b, 0xed, 0x28, 0xe2, 0x87, 0x20, 0xee, 0xfc, 0x52, 0xe4, 0x59, 0x7b, 0x37, 0x2c,
	0xbd, 0x20, 0x71, 0x5a, 0xcf, 0x9b, 0xb7, 0x6f, 0xde, 0xf3, 0x18, 0xc6, 0xb9, 0xce, 0x6c, 0xf6,
	0xfe, 0x90, 0x1b, 0xab, 0x51, 0xec, 0xae, 0xa8, 0x64, 0x6d, 0xfa, 0x4c, 0xce, 0x8a, 0x66, 0x2a,
	0x8e, 0x05, 0x3e, 0x19, 0x79, 0xb6, 0x41, 0x5d, 0x20, 0xc9, 0xaf, 0x26, 0xf4, 0xd6, 0xfe, 0x67,
	0x36, 0x86, 0xb6, 0x92, 0xb8, 0xb7, 0x3c, 0x9a, 0x46, 0xf3, 0xfe, 0xaa, 0x28, 0xd8, 0x2b, 0x18,
	0x06, 0xf9, 0xcd, 0x5e, 0xec, 0x90, 0x37, 0xa8, 0x3b, 0x08, 0xe0, 0x17, 0xb1, 0x43, 0xf6, 0x01,
	0xc6, 0x25, 0x49, 0xa2, 0xd9, 0x6a, 0x95, 0x5b, 0x95, 0xed, 0x79, 0x93, 0xb8, 0xe7, 0xa1, 0xb7,
	0xac, 0x5a, 0x8c, 0x41, 0x8b, 0xe4, 0x5a, 0x44, 0xa1, 0x33, 0x9b, 0x42, 0x7c, 0xfa, 0x77, 0x9b,
	0x5a, 0xa7, 0x10, 0x1b, 0x41, 0xf3, 0xa0, 0x53, 0xde, 0xa1, 0x8e, 0x3b, 0x3a, 0xd7, 0xb8, 0x13,
	0x2a, 0xe5, 0xdd, 0xc2, 0x35, 0x15, 0x6c, 0x06, 0x03, 0x89, 0xf7, 0xe2, 0x90, 0xda, 0x8d, 0x8b,
	0xcb, 0x7b, 0x41, 0x8a, 0xb0, 0xb5, 0x41, 0xcd, 0x5e, 0x02, 0x3c, 0x60, 0xb6, 0xd9, 0x66, 0x99,
	0x96, 0x86, 0xf7, 0x89, 0xd0, 0x7f, 0xc0, 0xec, 0x86, 0x00, 0xe7, 0x2f, 0x15, 0x47, 0xc3, 0x61,
	0x1a, 0xcd, 0xdb, 0x2b, 0x3a, 0xbb, 0x59, 0x4e, 0xcd, 0xf0, 0x98, 0xc0, 0xa2, 0x60, 0xd7, 0xd0,
	0xdb, 0xa1, 0x15, 0x52, 0x58, 0xc1, 0x07, 0xd3, 0x68, 0x1e, 0x2f, 0x2e, 0x8b, 0xeb, 0xbd, 0x0a,
	0x57, 0xfb, 0xd9, 0xb7, 0x57, 0x25, 0x91, 0x82, 0x28, 0xc9, 0x87, 0x3e, 0x88, 0x92, 0xec, 0x12,
	0xba, 0x4e, 0x6f, 0xa3, 0x24, 0x7f, 0x46, 0x68, 0xc7, 0x95, 0x9f, 0x64, 0xf2, 0x23, 0x82, 0x51,
	0x5d, 0xa9, 0x8a, 0x1d, 0x9d, 0xc6, 0x7e, 0x01, 0xfd, 0xa3, 0x7a, 0x54, 0x39, 0x4a, 0x25, 0xfc,
	0xa2, 0x2a, 0x80, 0x71, 0xe8, 0xda, 0xa3, 0xb2, 0x16, 0xb5, 0x5f, 0x4c, 0x28, 0xdd, 0x6c, 0x91,
	0xab, 0x8d, 0xbb, 0xda, 0x62, 0x1f, 0x1d, 0x91, 0xab, 0xb5, 0x4e, 0xd9, 0x04, 0x7a, 0xf7, 0x62,
	0x8b, 0x77, 0x59, 0xf6, 0xe8, 0xd7, 0x51, 0xd6, 0xc9, 0x12, 0x2e, 0x6e, 0x34, 0x0a, 0x8b, 0xc1,
	0xdc, 0x0a, 0xbf, 0x1d, 0xd0, 0x58, 0xf6, 0x16, 0x7a, 0x61, 0xe3, 0x64, 0x2f, 0x5e, 0x9c, 0xd5,
	0x2e, 0x64, 0x55, 0x12, 0x92, 0xd7, 0x70, 0x5e, 0x57, 0xc9, 0xd3, 0xef, 0xee, 0x7e, 0x50, 0x6b,
	0x9f, 0xce, 0x1d, 0x93, 0x37, 0xc0, 0x3e, 0xa2, 0xad, 0xcf, 0x7a, 0xf2, 0xd1, 0x26, 0x3f, 0x23,
	0x18, 0xfd, 0x41, 0x76, 0x92, 0xff, 0x62, 0x8b, 0xcd, 0xfc, 0xfa, 0x1b, 0xd3, 0xe6, 0x3c, 0x5e,
	0x0c, 0x3d, 0xf1, 0x56, 0x1c, 0xbf, 0xa2, 0xf5, 0xaf, 0x61, 0x16, 0x5e, 0x43, 0x93, 0x38, 0x71,
	0x10, 0x33, 0xa8, 0xc3, 0xd3, 0xf0, 0x29, 0x5a, 0x55, 0x8a, 0xe7, 0x30, 0xbe, 0x55, 0xa6, 0x74,
	0x66, 0x7c, 0x8e, 0x64, 0x0d, 0xac, 0x86, 0x3b, 0xcb, 0xef, 0xa0, 0x1f, 0x1c, 0x19, 0x1e, 0xd1,
	0x98, 0xbf, 0x3c, 0x57, 0x8c, 0x30, 0xae, 0x51, 0x8d, 0x5b, 0xc2, 0xc5, 0x3a, 0x97, 0xff, 0x61,
	0x47, 0x75, 0x95, 0x27, 0x77, 0x74, 0xd7, 0x21, 0x89, 0xeb, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x0c, 0x63, 0x9d, 0xc8, 0x98, 0x04, 0x00, 0x00,
}
