// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/welaw.proto

package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for WelawSvc service

type WelawSvcClient interface {
	// Auth
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error)
	LoginUser(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*LoginUserReply, error)
	MakeToken(ctx context.Context, in *MakeTokenRequest, opts ...grpc.CallOption) (*MakeTokenReply, error)
	LoginAs(ctx context.Context, in *LoginAsRequest, opts ...grpc.CallOption) (*LoginAsReply, error)
	Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutReply, error)
	// Ballot
	CreateVote(ctx context.Context, in *CreateVoteRequest, opts ...grpc.CallOption) (*CreateVoteReply, error)
	UpdateVote(ctx context.Context, in *UpdateVoteRequest, opts ...grpc.CallOption) (*UpdateVoteReply, error)
	GetVote(ctx context.Context, in *GetVoteRequest, opts ...grpc.CallOption) (*GetVoteReply, error)
	DeleteVote(ctx context.Context, in *DeleteVoteRequest, opts ...grpc.CallOption) (*DeleteVoteReply, error)
	ListVotes(ctx context.Context, in *ListVotesRequest, opts ...grpc.CallOption) (*ListVotesReply, error)
	// Law
	CreateLaw(ctx context.Context, in *CreateLawRequest, opts ...grpc.CallOption) (*CreateLawReply, error)
	// rpc ListVersions(ListVersionsRequest) returns (ListVersionsReply) {}
	GetLaw(ctx context.Context, in *GetLawRequest, opts ...grpc.CallOption) (*GetLawReply, error)
	ListLaws(ctx context.Context, in *ListLawsRequest, opts ...grpc.CallOption) (*ListLawsReply, error)
	// Upstream
	CreateUpstream(ctx context.Context, in *CreateUpstreamRequest, opts ...grpc.CallOption) (*CreateUpstreamReply, error)
	GetUpstream(ctx context.Context, in *GetUpstreamRequest, opts ...grpc.CallOption) (*GetUpstreamReply, error)
	ListUpstreams(ctx context.Context, in *ListUpstreamsRequest, opts ...grpc.CallOption) (*ListUpstreamsReply, error)
	UpdateUpstream(ctx context.Context, in *UpdateUpstreamRequest, opts ...grpc.CallOption) (*UpdateUpstreamReply, error)
	// User
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserReply, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserReply, error)
	ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersReply, error)
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserReply, error)
}

type welawSvcClient struct {
	cc *grpc.ClientConn
}

func NewWelawSvcClient(cc *grpc.ClientConn) WelawSvcClient {
	return &welawSvcClient{cc}
}

func (c *welawSvcClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error) {
	out := new(LoginReply)
	err := grpc.Invoke(ctx, "/proto.WelawSvc/Login", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *welawSvcClient) LoginUser(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*LoginUserReply, error) {
	out := new(LoginUserReply)
	err := grpc.Invoke(ctx, "/proto.WelawSvc/LoginUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *welawSvcClient) MakeToken(ctx context.Context, in *MakeTokenRequest, opts ...grpc.CallOption) (*MakeTokenReply, error) {
	out := new(MakeTokenReply)
	err := grpc.Invoke(ctx, "/proto.WelawSvc/MakeToken", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *welawSvcClient) LoginAs(ctx context.Context, in *LoginAsRequest, opts ...grpc.CallOption) (*LoginAsReply, error) {
	out := new(LoginAsReply)
	err := grpc.Invoke(ctx, "/proto.WelawSvc/LoginAs", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *welawSvcClient) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutReply, error) {
	out := new(LogoutReply)
	err := grpc.Invoke(ctx, "/proto.WelawSvc/Logout", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *welawSvcClient) CreateVote(ctx context.Context, in *CreateVoteRequest, opts ...grpc.CallOption) (*CreateVoteReply, error) {
	out := new(CreateVoteReply)
	err := grpc.Invoke(ctx, "/proto.WelawSvc/CreateVote", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *welawSvcClient) UpdateVote(ctx context.Context, in *UpdateVoteRequest, opts ...grpc.CallOption) (*UpdateVoteReply, error) {
	out := new(UpdateVoteReply)
	err := grpc.Invoke(ctx, "/proto.WelawSvc/UpdateVote", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *welawSvcClient) GetVote(ctx context.Context, in *GetVoteRequest, opts ...grpc.CallOption) (*GetVoteReply, error) {
	out := new(GetVoteReply)
	err := grpc.Invoke(ctx, "/proto.WelawSvc/GetVote", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *welawSvcClient) DeleteVote(ctx context.Context, in *DeleteVoteRequest, opts ...grpc.CallOption) (*DeleteVoteReply, error) {
	out := new(DeleteVoteReply)
	err := grpc.Invoke(ctx, "/proto.WelawSvc/DeleteVote", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *welawSvcClient) ListVotes(ctx context.Context, in *ListVotesRequest, opts ...grpc.CallOption) (*ListVotesReply, error) {
	out := new(ListVotesReply)
	err := grpc.Invoke(ctx, "/proto.WelawSvc/ListVotes", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *welawSvcClient) CreateLaw(ctx context.Context, in *CreateLawRequest, opts ...grpc.CallOption) (*CreateLawReply, error) {
	out := new(CreateLawReply)
	err := grpc.Invoke(ctx, "/proto.WelawSvc/CreateLaw", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *welawSvcClient) GetLaw(ctx context.Context, in *GetLawRequest, opts ...grpc.CallOption) (*GetLawReply, error) {
	out := new(GetLawReply)
	err := grpc.Invoke(ctx, "/proto.WelawSvc/GetLaw", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *welawSvcClient) ListLaws(ctx context.Context, in *ListLawsRequest, opts ...grpc.CallOption) (*ListLawsReply, error) {
	out := new(ListLawsReply)
	err := grpc.Invoke(ctx, "/proto.WelawSvc/ListLaws", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *welawSvcClient) CreateUpstream(ctx context.Context, in *CreateUpstreamRequest, opts ...grpc.CallOption) (*CreateUpstreamReply, error) {
	out := new(CreateUpstreamReply)
	err := grpc.Invoke(ctx, "/proto.WelawSvc/CreateUpstream", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *welawSvcClient) GetUpstream(ctx context.Context, in *GetUpstreamRequest, opts ...grpc.CallOption) (*GetUpstreamReply, error) {
	out := new(GetUpstreamReply)
	err := grpc.Invoke(ctx, "/proto.WelawSvc/GetUpstream", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *welawSvcClient) ListUpstreams(ctx context.Context, in *ListUpstreamsRequest, opts ...grpc.CallOption) (*ListUpstreamsReply, error) {
	out := new(ListUpstreamsReply)
	err := grpc.Invoke(ctx, "/proto.WelawSvc/ListUpstreams", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *welawSvcClient) UpdateUpstream(ctx context.Context, in *UpdateUpstreamRequest, opts ...grpc.CallOption) (*UpdateUpstreamReply, error) {
	out := new(UpdateUpstreamReply)
	err := grpc.Invoke(ctx, "/proto.WelawSvc/UpdateUpstream", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *welawSvcClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserReply, error) {
	out := new(CreateUserReply)
	err := grpc.Invoke(ctx, "/proto.WelawSvc/CreateUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *welawSvcClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserReply, error) {
	out := new(GetUserReply)
	err := grpc.Invoke(ctx, "/proto.WelawSvc/GetUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *welawSvcClient) ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersReply, error) {
	out := new(ListUsersReply)
	err := grpc.Invoke(ctx, "/proto.WelawSvc/ListUsers", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *welawSvcClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserReply, error) {
	out := new(UpdateUserReply)
	err := grpc.Invoke(ctx, "/proto.WelawSvc/UpdateUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for WelawSvc service

type WelawSvcServer interface {
	// Auth
	Login(context.Context, *LoginRequest) (*LoginReply, error)
	LoginUser(context.Context, *LoginUserRequest) (*LoginUserReply, error)
	MakeToken(context.Context, *MakeTokenRequest) (*MakeTokenReply, error)
	LoginAs(context.Context, *LoginAsRequest) (*LoginAsReply, error)
	Logout(context.Context, *LogoutRequest) (*LogoutReply, error)
	// Ballot
	CreateVote(context.Context, *CreateVoteRequest) (*CreateVoteReply, error)
	UpdateVote(context.Context, *UpdateVoteRequest) (*UpdateVoteReply, error)
	GetVote(context.Context, *GetVoteRequest) (*GetVoteReply, error)
	DeleteVote(context.Context, *DeleteVoteRequest) (*DeleteVoteReply, error)
	ListVotes(context.Context, *ListVotesRequest) (*ListVotesReply, error)
	// Law
	CreateLaw(context.Context, *CreateLawRequest) (*CreateLawReply, error)
	// rpc ListVersions(ListVersionsRequest) returns (ListVersionsReply) {}
	GetLaw(context.Context, *GetLawRequest) (*GetLawReply, error)
	ListLaws(context.Context, *ListLawsRequest) (*ListLawsReply, error)
	// Upstream
	CreateUpstream(context.Context, *CreateUpstreamRequest) (*CreateUpstreamReply, error)
	GetUpstream(context.Context, *GetUpstreamRequest) (*GetUpstreamReply, error)
	ListUpstreams(context.Context, *ListUpstreamsRequest) (*ListUpstreamsReply, error)
	UpdateUpstream(context.Context, *UpdateUpstreamRequest) (*UpdateUpstreamReply, error)
	// User
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserReply, error)
	GetUser(context.Context, *GetUserRequest) (*GetUserReply, error)
	ListUsers(context.Context, *ListUsersRequest) (*ListUsersReply, error)
	UpdateUser(context.Context, *UpdateUserRequest) (*UpdateUserReply, error)
}

func RegisterWelawSvcServer(s *grpc.Server, srv WelawSvcServer) {
	s.RegisterService(&_WelawSvc_serviceDesc, srv)
}

func _WelawSvc_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WelawSvcServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.WelawSvc/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WelawSvcServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WelawSvc_LoginUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WelawSvcServer).LoginUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.WelawSvc/LoginUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WelawSvcServer).LoginUser(ctx, req.(*LoginUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WelawSvc_MakeToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MakeTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WelawSvcServer).MakeToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.WelawSvc/MakeToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WelawSvcServer).MakeToken(ctx, req.(*MakeTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WelawSvc_LoginAs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginAsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WelawSvcServer).LoginAs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.WelawSvc/LoginAs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WelawSvcServer).LoginAs(ctx, req.(*LoginAsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WelawSvc_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WelawSvcServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.WelawSvc/Logout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WelawSvcServer).Logout(ctx, req.(*LogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WelawSvc_CreateVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WelawSvcServer).CreateVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.WelawSvc/CreateVote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WelawSvcServer).CreateVote(ctx, req.(*CreateVoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WelawSvc_UpdateVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateVoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WelawSvcServer).UpdateVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.WelawSvc/UpdateVote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WelawSvcServer).UpdateVote(ctx, req.(*UpdateVoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WelawSvc_GetVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WelawSvcServer).GetVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.WelawSvc/GetVote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WelawSvcServer).GetVote(ctx, req.(*GetVoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WelawSvc_DeleteVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WelawSvcServer).DeleteVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.WelawSvc/DeleteVote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WelawSvcServer).DeleteVote(ctx, req.(*DeleteVoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WelawSvc_ListVotes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVotesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WelawSvcServer).ListVotes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.WelawSvc/ListVotes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WelawSvcServer).ListVotes(ctx, req.(*ListVotesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WelawSvc_CreateLaw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLawRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WelawSvcServer).CreateLaw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.WelawSvc/CreateLaw",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WelawSvcServer).CreateLaw(ctx, req.(*CreateLawRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WelawSvc_GetLaw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLawRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WelawSvcServer).GetLaw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.WelawSvc/GetLaw",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WelawSvcServer).GetLaw(ctx, req.(*GetLawRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WelawSvc_ListLaws_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLawsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WelawSvcServer).ListLaws(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.WelawSvc/ListLaws",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WelawSvcServer).ListLaws(ctx, req.(*ListLawsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WelawSvc_CreateUpstream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUpstreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WelawSvcServer).CreateUpstream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.WelawSvc/CreateUpstream",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WelawSvcServer).CreateUpstream(ctx, req.(*CreateUpstreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WelawSvc_GetUpstream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUpstreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WelawSvcServer).GetUpstream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.WelawSvc/GetUpstream",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WelawSvcServer).GetUpstream(ctx, req.(*GetUpstreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WelawSvc_ListUpstreams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUpstreamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WelawSvcServer).ListUpstreams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.WelawSvc/ListUpstreams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WelawSvcServer).ListUpstreams(ctx, req.(*ListUpstreamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WelawSvc_UpdateUpstream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUpstreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WelawSvcServer).UpdateUpstream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.WelawSvc/UpdateUpstream",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WelawSvcServer).UpdateUpstream(ctx, req.(*UpdateUpstreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WelawSvc_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WelawSvcServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.WelawSvc/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WelawSvcServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WelawSvc_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WelawSvcServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.WelawSvc/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WelawSvcServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WelawSvc_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WelawSvcServer).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.WelawSvc/ListUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WelawSvcServer).ListUsers(ctx, req.(*ListUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WelawSvc_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WelawSvcServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.WelawSvc/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WelawSvcServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WelawSvc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.WelawSvc",
	HandlerType: (*WelawSvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _WelawSvc_Login_Handler,
		},
		{
			MethodName: "LoginUser",
			Handler:    _WelawSvc_LoginUser_Handler,
		},
		{
			MethodName: "MakeToken",
			Handler:    _WelawSvc_MakeToken_Handler,
		},
		{
			MethodName: "LoginAs",
			Handler:    _WelawSvc_LoginAs_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _WelawSvc_Logout_Handler,
		},
		{
			MethodName: "CreateVote",
			Handler:    _WelawSvc_CreateVote_Handler,
		},
		{
			MethodName: "UpdateVote",
			Handler:    _WelawSvc_UpdateVote_Handler,
		},
		{
			MethodName: "GetVote",
			Handler:    _WelawSvc_GetVote_Handler,
		},
		{
			MethodName: "DeleteVote",
			Handler:    _WelawSvc_DeleteVote_Handler,
		},
		{
			MethodName: "ListVotes",
			Handler:    _WelawSvc_ListVotes_Handler,
		},
		{
			MethodName: "CreateLaw",
			Handler:    _WelawSvc_CreateLaw_Handler,
		},
		{
			MethodName: "GetLaw",
			Handler:    _WelawSvc_GetLaw_Handler,
		},
		{
			MethodName: "ListLaws",
			Handler:    _WelawSvc_ListLaws_Handler,
		},
		{
			MethodName: "CreateUpstream",
			Handler:    _WelawSvc_CreateUpstream_Handler,
		},
		{
			MethodName: "GetUpstream",
			Handler:    _WelawSvc_GetUpstream_Handler,
		},
		{
			MethodName: "ListUpstreams",
			Handler:    _WelawSvc_ListUpstreams_Handler,
		},
		{
			MethodName: "UpdateUpstream",
			Handler:    _WelawSvc_UpdateUpstream_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _WelawSvc_CreateUser_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _WelawSvc_GetUser_Handler,
		},
		{
			MethodName: "ListUsers",
			Handler:    _WelawSvc_ListUsers_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _WelawSvc_UpdateUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/welaw.proto",
}

func init() { proto1.RegisterFile("proto/welaw.proto", fileDescriptor7) }

var fileDescriptor7 = []byte{
	// 448 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x94, 0xdd, 0x6a, 0xdb, 0x30,
	0x14, 0xc7, 0x77, 0x93, 0x2c, 0xd3, 0xd8, 0x47, 0x14, 0x2f, 0x59, 0xbc, 0x5d, 0xed, 0x01, 0x32,
	0xf6, 0x01, 0x83, 0xc1, 0x60, 0x21, 0x83, 0x30, 0x70, 0x6f, 0xda, 0xa6, 0xbd, 0x56, 0xda, 0x43,
	0x1a, 0xe2, 0x46, 0xae, 0x25, 0xd7, 0xf4, 0xf1, 0xfa, 0x66, 0xc5, 0x3a, 0xd6, 0xd7, 0xb1, 0x7b,
	0xd5, 0xfa, 0xf7, 0xf7, 0xef, 0xe8, 0x9c, 0x48, 0x32, 0x1b, 0x17, 0xa5, 0xd4, 0xf2, 0x6b, 0x0d,
	0xb9, 0xa8, 0x17, 0xe6, 0x7f, 0x3e, 0x30, 0x7f, 0xd2, 0xf7, 0x98, 0x88, 0x4a, 0xdf, 0x60, 0x90,
	0x72, 0x24, 0x5b, 0x91, 0xe7, 0x52, 0xb7, 0xec, 0x1d, 0x32, 0x67, 0x5b, 0xad, 0x52, 0x50, 0xb6,
	0x24, 0x69, 0x49, 0xa1, 0x74, 0x09, 0xe2, 0x16, 0xe9, 0xf7, 0x47, 0xc6, 0x46, 0x97, 0xcd, 0xaa,
	0x67, 0xf7, 0x57, 0xfc, 0x1b, 0x1b, 0x64, 0x72, 0xb7, 0x3f, 0xf2, 0x09, 0xa6, 0x0b, 0xf3, 0x74,
	0x0a, 0x77, 0x15, 0x28, 0x9d, 0x8e, 0x63, 0x58, 0xe4, 0x0f, 0x5f, 0x5e, 0xf0, 0x3f, 0xec, 0x95,
	0x79, 0xde, 0x28, 0x28, 0xf9, 0x2c, 0x7c, 0xa3, 0x21, 0x56, 0xfd, 0xd0, 0x0d, 0x9c, 0x7e, 0x22,
	0x0e, 0x70, 0x2e, 0x0f, 0x70, 0x74, 0xba, 0x23, 0x54, 0x0f, 0x02, 0xd4, 0x7f, 0xb1, 0x97, 0xa6,
	0xe4, 0x52, 0xf1, 0x68, 0x89, 0xa5, 0xb2, 0xea, 0x84, 0x62, 0x14, 0x7f, 0xb2, 0x61, 0x26, 0x77,
	0xb2, 0xd2, 0x3c, 0xf1, 0x2f, 0xc8, 0x4a, 0x5b, 0x8d, 0x13, 0x8a, 0xd6, 0x5f, 0xc6, 0x56, 0x25,
	0x08, 0x0d, 0x17, 0x52, 0x03, 0xff, 0xd8, 0xbe, 0xe3, 0x91, 0xb5, 0xa7, 0x3d, 0x89, 0xab, 0xb0,
	0x29, 0xae, 0x69, 0x05, 0x8f, 0x68, 0x85, 0x30, 0x71, 0x23, 0xaf, 0x41, 0x1b, 0xdd, 0x8e, 0xdc,
	0x3e, 0xd3, 0x91, 0x1d, 0x76, 0x4b, 0xff, 0x83, 0x1c, 0xc8, 0xd2, 0x1e, 0xd1, 0xa5, 0xc3, 0xc4,
	0xef, 0xf5, 0x5e, 0x99, 0xa2, 0xca, 0xef, 0xb5, 0x25, 0x9d, 0xbd, 0xf6, 0x81, 0xd3, 0xf1, 0x07,
	0xc9, 0x44, 0xed, 0x74, 0x47, 0xa8, 0x1e, 0x04, 0x6e, 0xcb, 0xd6, 0xa0, 0x1b, 0x37, 0xf1, 0x03,
	0x06, 0x22, 0x27, 0x14, 0xad, 0xdf, 0x6c, 0xd4, 0x34, 0x92, 0x89, 0x5a, 0xf1, 0x69, 0xd0, 0x59,
	0x03, 0xac, 0x99, 0x74, 0x38, 0xba, 0x19, 0x7b, 0x8b, 0x5d, 0x6c, 0xda, 0x3b, 0xc3, 0x3f, 0x47,
	0xcd, 0x59, 0x6c, 0xeb, 0xa4, 0xcf, 0xa4, 0x58, 0x6d, 0xc5, 0x5e, 0xaf, 0x41, 0xbb, 0x52, 0x73,
	0xdf, 0x2e, 0xad, 0x33, 0xeb, 0x8b, 0xb0, 0xc8, 0x7f, 0xf6, 0xa6, 0xe9, 0xd2, 0x62, 0xc5, 0x3f,
	0x05, 0xbd, 0x3b, 0x6a, 0x0b, 0xcd, 0xfb, 0x43, 0x37, 0x1d, 0x9e, 0xae, 0xce, 0x74, 0x31, 0xa6,
	0xd3, 0xd1, 0x94, 0x5c, 0x0d, 0xf3, 0x21, 0x88, 0xaf, 0x46, 0xf8, 0x25, 0x98, 0xf6, 0x24, 0xe1,
	0xc1, 0x36, 0x7a, 0x70, 0xb0, 0x43, 0x77, 0x42, 0x71, 0x74, 0x2c, 0x1b, 0x14, 0x1f, 0x4b, 0x43,
	0xfa, 0x8e, 0x65, 0x1b, 0x90, 0x2b, 0x19, 0x75, 0xee, 0x51, 0xff, 0x95, 0x0c, 0x1a, 0xd8, 0x0e,
	0x4d, 0xf0, 0xe3, 0x29, 0x00, 0x00, 0xff, 0xff, 0xf7, 0x18, 0x8d, 0xe6, 0xc5, 0x05, 0x00, 0x00,
}
